### ISSUE TITLE
Плагин вылетает при подсчете размера папок на FTP-сервере

### ISSUE THREAD

**Issue by PaperbackWriter1** [michaellukashov/Far-NetBox#133]
NetBox 2.1.40 (build 352), версия x64
зашел на FTP-сервер, пометил insert'ом две папки, содержащие внутри себя подпапки и файлы,
нажал F3, чтобы узнать их размер.
В процессе подсчета размера Far выдал ошибку:
![netbox_exception_occured](https://cloud.githubusercontent.com/assets/7480134/4934306/29d40566-65a0-11e4-9ded-960b0fe5da28.png)
При нажатии "Debug" Far завис и Windows 7 x64 закрыл программу.

Баг проявляется не всегда, после открытия Far'а заново плагин нормально посчитал размер на тех же самых папках.
Суммарный размер помеченных папок - 1 гигабайт.

**Comment by PaperbackWriter1** [comment]
После установки последней версии 2.1.41 (build 365) вроде бы прекратилось.

**Comment by VictorVG** [comment]
Да, эта ошибка уже давно не наблюдается.
