### ISSUE TITLE
Нет диалога подтверждения перезаписи файла. Настройки игнорируются.

### ISSUE THREAD

**Issue by shadowlmd** [michaellukashov/Far-NetBox#137]
Сабж. WebDAV. Файлы молча перезаписываются без каких-либо подтверждений.

![image](https://cloud.githubusercontent.com/assets/969156/5372885/e384c25e-8060-11e4-8f66-95ce9a62f04e.png)

**Comment by bertmsk** [comment]
nextbox невероятно глюкавое поделие

**Comment by VictorVG** [comment]
Так если посмотреть выставленные настройки то видим что стоит настройка _Overwirting of files == On_ - _Перезаписывать файлы == Да_ которая не должна спрашивать подтверждения. Запрос выводится если она стоит в третьем состоянии [?] и в настройках Far стоит спрашивать подтверждение. Так исходно задумано ещё в первой версии NetBox. Так что настройка работает ожидаемо.  А не сохранение локальных настроек может быть вызвано например вашими скриптами или локальным ACL что вы в данном случае не учли. Так что уточнить причину событий исходя из вашего описания я не возьмусь поскольку оно слишком неточное.

**Comment by shadowlmd** [comment]
Вообще-то, этот диалог о том, в каких случаях спрашивать подтверждение. И [X] означает "спрашивать", [ ] -- не спрашивать, [?] -- использовать настройки FAR. Не знаю, какие там могут быть ACL, учитывая, что все остальные настройки сохранялись, а эта нет, а FAR хранит настройки в sqlite базе. Сейчас настройка сохраняется, но проверить её работу не получилось:
![screenshot from 2016-08-30 13-51-05](https://cloud.githubusercontent.com/assets/969156/18086553/34c433b4-6eb9-11e6-8047-bef9e58e78a8.png)

**Comment by VictorVG** [comment]
_ACL == Access Control List - "Список Контроля Доступа"_ на жаргоне "_права_".  Может там была ошибка, либо как возможный вариант совпали два события "_Предыдущая операция с БД зависла_" и "_Запись NetBox в БД_" что привело к потере транзакции. Сейчас мы это не сможем проверить - событие прошло, а ОС логов таких операций не ведёт :( , а было бы полезно их глянуть - может эта гипотеза ошибочна и имело место иное событие про которое мы уже никогда не узнаем?

Ну и просто причиной могут быть ошибки самого Far.exe b4700. Текущие билды - СТАБЛЕ b4747, НОЧНУШКА b4771. Обновить путём копирования рабочей копии в иной каталог и перезаписи в новой копии бинарников поверх дело не сложное, тут придётся только до первого запуска копии удалить plugincache*.db* в профиле. А далее посмотреть что будет происходить? У меня встречались случаи когда вроде одна и та же копия в одном каталоге чудила, а после её копирования в иной и с удалением кэша все странности испарялись будто их никогда и не было. Иной раз для их устранения приходилось перезапускать ось либо роутер - ну, тут по месту...

**Comment by shadowlmd** [comment]
Что такое ACL, я знаю. :) Не понятно было, как это применимо к этому багу. Проверил на свежей версии фара, диалог появляется, так что уже не актуально.

**Comment by VictorVG** [comment]
Кстати, один случай я и сам получил, но то была моя вина - я сказал чтобы не выводился больше запрос перезаписи - хватило. Сбросил настройки - вернул.
