### ISSUE TITLE
SSH ECDSA keys support

### ISSUE THREAD

**Issue by AnrDaemon** [michaellukashov/Far-NetBox#148]
Добавить поддержку ECDSA ключей было бы очень нелишним делом.
Потихоньку начинаю натыкаться на серверы, принимающие только такие ключи.
Пока их мало, и надобности в работе с ними невелики, можно поюзать OpenSSH, но количество таких серверов растёт…

**Comment by VictorVG** [comment]
Подумать в данную сторону можно, на там могут вылезти патентные ограничения связанные с реализацией RFC5656. Наверное стоит для начала убедится в том, что после реализации не появится кто-то типа Rambus LTD. и не заявит что "А на всё это у меня патенты есть! Платите мне роялити!" (лицензионные отчисления патентодержателю) - сей номер она проделала с памятью DRAM - её люди сидели в комитете JDEC и компания патентовала всё, что там обсуждалось, а после выкатила все отрасли претензии. Micron, Infinion, Hinix согласились ей платить, а вот с Hyndy и Samsung у неё сей номер не прошёл - Rambus попыталась заставить их платить, её понятно послали лесом, она попыталась добиться своего через суд - " Меня есть патенты! Они обязаны мне платить роялити!", а те подали на Rambus встречный судебный иск о необоснованности патентования публично-известных технических решений JDEC и судья приостановил действие её патентов на DRAM, но сия контора почти полтора десятка лет получала с производителей чипов памяти роялити.:) При американском патентом праве такая ситуация очень вероятна ибо им достаточно только подачи заявки на патент и уже с момента её регистрации пользователь обязан платить роялити. Причём независимо от результатов её рассмотрения - в этом смысле фраза *"Заявка на патенты подана."* тождественно равна фразе *Платите нам за всё!"*.:)

**Comment by AnrDaemon** [comment]
Я в курсе этой свистопляски.
Просто повесил тут для галочки. Прилепи лейблик "виш", пусть повисит, пока авторы PuTTY/WinSCP не прокачают код.

**Comment by VictorVG** [comment]
Да, думаю как предложение не помешает, ну и если кто не в курсе истории с патентами на DRAM сможет представить себе ситуацию и надеюсь не наступит на грабли.

**Comment by AnrDaemon** [comment]
Solved in recent base library versions.
