### ISSUE TITLE
windows 10: not storing server key fingerprint

### ISSUE THREAD

**Issue by brammator** [michaellukashov/Far-NetBox#158]
Каждый раз, когда я подключаюсь к серверу, NetBox предупреждает меня о неизвестном ключе и предлагает его сохранить.  Но не сохраняет - в следующий раз вылетает такое же предупреждение.

**Comment by michaellukashov** [comment]
Плагин точно последней версии? Эта ошибка была исправлена в версии 2.1.43.392 от 14.07.2015

**Comment by brammator** [comment]
Да, в ночном билде FAR3 плагин исправлен.  Виноват, не проверил.
