### ISSUE TITLE
windows 10: crash on connecting via ssh tunnel

### ISSUE THREAD

**Issue by brammator** [michaellukashov/Far-NetBox#159]
Exception:   Access violation (read from 0x0000000000000012)
Address:     0x00007FFCC27D27AC
Function:    ProcessPanelInputW
Module:      \Program Files\Far Manager\Plugins\NetBox\NetBox.dll

На каждой попытке соединиться с сервером через ssh туннель.  Вне зависимости от того, какая авторизация на сервере туннеля (.ppk, .ppk с паролем, вбитый в настройки пароль, интерактивно запрашиваемый пароль).  Судя по логам сервера, крашится именно на авторизации с туннельным сервером.  В седьмой винде работало (и работает).  Напрямую (без тоннеля) тоже работает.

**Comment by michaellukashov** [comment]
Эта ошибка тоже была исправлена. Возьмите последнюю версию плагина из ночной сборки Far

**Comment by brammator** [comment]
Да, действительно, в ночных билдах не проверил.  Прошу прощения.
