### ISSUE TITLE
WIndows10: SCP/SCFP crash, FTP jumps back to local FS when changing folders

### ISSUE THREAD

**Issue by kartu** [michaellukashov/Far-NetBox#168]
NetBox 2.1.44.411 10.10.2015

FTP works until you try to change folder, after which it jumps back to local filesystem.

Attempt to open SCP/SFTP immediately triggers "has stopped working" error window.

![netbox-crash](https://cloud.githubusercontent.com/assets/6850149/10870537/8042ca1a-80cd-11e5-95e0-d3b9dc377dc0.png)

**Comment by VictorVG** [comment]
If the remote server located on your local subnet Class A (CIDR = 10/8) more than the IP that has, for example FTP, it would be nice to attach logs to include logging settings NetBox, time, and try to update to version 2.1.44.412 on 10/26/2015 such as will not interfere, and a bit more clear obhyasnit that you have on your newfangled OS happening. We're conservative people, we must work and not for the new advertising idiocy chase, so that once you have it is a miracle Redmond thought - ask clear explanation of what you see.

**Comment by kartu** [comment]
Сервер в локальной сети и никаких проблем с сеткой нет (другие клиенты, в том числе с той же машины работают)

После отключения кешинга, заработал простой ФТП.

Ставить последнюю версию плагина, вместо той, что идёт с фаром, пробовал: в этом случае фар просто не видит плагин. 

Попробовал как с "проинсталиррованым" фаром (в програм файлс) так и с просто разархивированым. ^^

Попробую включить логи.

ЗЫ
ОС как ОС, кроме настойчивого желания системы обновить драйверы и проблемы с нетбоксом, все замечательно. =)

**Comment by VictorVG** [comment]
Так, а вы обратили внимание на то что должны совпадать разрядность и платформа [**Общие сведения о совместимости FAR и плагинов**](http://forum.ru-board.com/topic.cgi?forum=5&topic=31718&start=0&limit=1&m=1#1)? Сборки для Far3 надо брать или из [**"ночнушек"**](http://www.farmanager.com/download.php?l=ru) (проще всего из 7-Zip, от Far2 не запустятся)  или у меня они есть (я их собираю из исходников, текущая версия 2.1.44.412, если изменится ссылка на архив то можно просто посмотреть в [**каталоге**](https://yadi.sk/d/oc1fPSIbhvvwT) на YandexDisk):

[**FarNetBox-2.1.44_Far3_x64.7z**](https://yadi.sk/d/o7IMvO8qicPvo)
[**FarNetBox-2.1.44_Far3_x86.7z**](https://yadi.sk/d/BxNBP9WGicPwe)

**Comment by kartu** [comment]
Обращал, конечно. Даже "на всякий случай" обе разрядности попробовал "мало ли"... =)

Сегодня ещё раз перепробую, отпишусь с логами.

**Comment by VictorVG** [comment]
Пара должна быть совместимой или не запустится.

**Comment by kartu** [comment]
Текущая версия в последнем "стабильном" фаре:


SCP log:

2015-11-02 19:32:34.465 Enumerating network events for socket 544
. 2015-11-02 19:32:34.465 Enumerated 1 network events making 1 cumulative events for socket 544
. 2015-11-02 19:32:34.465 Handling network read event on socket 544 with error 0
. 2015-11-02 19:32:34.465 Server version: SSH-2.0-dropbear_2015.67
. 2015-11-02 19:32:34.465 We believe remote version has SSH-2 channel request bug
. 2015-11-02 19:32:34.465 Using SSH protocol version 2
. 2015-11-02 19:32:34.465 We claim version: SSH-2.0-NetBox_FAR_release_2.1.44
. 2015-11-02 19:32:34.477 Selecting events 0 for socket 544
. 2015-11-02 19:32:34.477 Couldn't agree a key exchange algorithm ((available: curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,kexguess2@matt.ucc.asn.au)


Глюк с кэшированием папок повторить не смог.

**Comment by VictorVG** [comment]
**@kartu**

Т.е. можно предположить что вылезли проблемы совместимости с новой ОС - об этом уже многое говорит, и не только в Фар. Вероятно что часть из них порожденая вот этим - [**Deprecated or legacy APIs**](https://msdn.microsoft.com/en-us/library/windows/desktop/ff818516%28v=vs.85%29.aspx#deprecated_or_legacy_apis) - иначе их Windows Store созданный для только того, чтобы всё ПО находилось под полным контролем Микрософт никому и даром не будет нужен. А если всё под их контролем они могут делать что хотят и самое интересное что пользователь обязан с этим согласится согласно их *EULA* и *Соглашению о конфиденциальности*, а их суммарная ответственность не превышает $10 самом худшем случае - ведь они отвечают только за то, что программа на момент её выпуска запускается. :)

**Comment by kartu** [comment]
" Couldn't agree a key exchange algorithm"?

**Comment by VictorVG** [comment]
Так у вас в логе прямо написано:

>. 2015-11-02 19:32:34.465 Server version: SSH-2.0-dropbear_2015.67
>. 2015-11-02 19:32:34.465 We believe remote version has SSH-2 channel request bug

что используется [**Dropbear SSH**](https://matt.ucc.asn.au/dropbear/dropbear.html) с собственной урезанной реализацией стека протоколов SSH2. Это я виноват сразу не вчитался в лог, а то бы поняли что происходит. :(

**Comment by kartu** [comment]
Это объясняет последующий вылет с убиением процесса"?

**Comment by VictorVG** [comment]
Вполне если в процессе работы возникло [**Exception 0xC0000417**](https://github.com/michaellukashov/Far-NetBox/issues/166) - ядро ОС инициирует аварийное завершение сбойной задачи.

**Comment by kartu** [comment]
Ок. баг с ФТП повторить не получается, с SCP проблема с вылетом уже известна, закрываю.

**Comment by VictorVG** [comment]
Похоже явление из инц #166 и у вас проявилось...

**Comment by VictorVG** [comment]
Проверяйте:

[**FarNetBox-2.1.44_Far3_x64.7z**](https://yadi.sk/d/o7IMvO8qicPvo)
[**FarNetBox-2.1.44_Far3_x86.7z**](https://yadi.sk/d/BxNBP9WGicPwe)

более-менее всё вместе (без FarColorer, код оптимизирован, предпочтение на минимальный размер, собрано в VC++ 2010, постоянная ссылка) [**Far30latest-x86_x64-bin.7z**](https://yadi.sk/d/Qxnj9aw6gWc7e)

**Comment by VictorVG** [comment]
SCP починен - только что репортер обнаруживший данное явление сообщил. С переходом каталогов - у себя такое не наблюдаю, хотя если сделать операцию cd ../ а затем находясь в корне FTP нажать Enter происходит выход в локальную ФС. Но я это давно наблюдаю и по моему это фокусы одного из моих скриптов. Просто как известному коту из рекламы "*А ещё я вышивать умею, и на машинке. Только неохота!*" не охота копаться в этом хозяйстве без серьёзного повода типа поломки или рефакторинга в макрохозяйстве. :)
