### ISSUE TITLE
Bookmarks are not preserved between FAR sessions

### ISSUE THREAD

**Issue by martinprikryl** [michaellukashov/Far-NetBox#174]
- Connect (SFTP in my case)
- Plugin commands > NetBox commands > Add bookmark
- Manage bookmarks window opens with the bookmark added (my first bookmark)
- Disconnect session (by opening a local folder)
- Connect the same session
- Plugin commands > NetBox commands > Open directory
- The bookmark is there
- Save configuration Shift-F9 (just in case, have auto saving enabled anyway)
- Exit FAR (F10)
- Start FAR again
- Connect the same session
- Plugin commands > NetBox commands > Open directory
- No bookmarks there

NetBox 2.1.45.416
FAR 3.0 build 4455 x86

**Comment by michaellukashov** [comment]
Fixed in 2.1.45.418

**Comment by martinprikryl** [comment]
Sorry for late answer. I got a chance to test it only now. Though, unfortunately I can see no difference. If I follow the steps from my initial report, the behavior is identical as before.

NetBox 2.1.45 build 420
FAR 3.0 build 4510 x86

**Comment by martinprikryl** [comment]
Thanks. It works now.
