### ISSUE TITLE
Расширение диалога атрибутов для симлинков

### ISSUE THREAD

**Issue by lazyhamster** [michaellukashov/Far-NetBox#175]
Сделал небольшой патчик, который добавляет в диалог атрибутов для симлинков информацию, куда, собственно, этот симлинк указывает. Принцип такой же как и в Фаре для локальных линков. Иногда удобно посмотреть куда линк ведет не заходя в каталог (особенно, учитывая неудобную навигацию по линкам в текущей реализации).

[attr_linkto_patch.txt](https://github.com/michaellukashov/Far-NetBox/files/59224/attr_linkto_patch.txt)
Патч делал на ветке far3.

**Comment by VictorVG** [comment]
Я лично "ЗА" его применение. Протестить можно и на моём FTP (поднят на роутере ZyXEL Keenetic EXTRA под LINUX) сразу увидим как себя ведёт. ОС на роутере просила поставить подкачку, ладно, поставил винт, так чего бы не пднять там FTP?:)

**Comment by michaellukashov** [comment]
Спасибо. Но было бы удобнее оформлять изменения в виде Pull request, как это принято на гитхабе.

**Comment by lazyhamster** [comment]
OK, без проблем. Буду делать pull request-ами.

**Comment by lazyhamster** [comment]
Переделал патч на pull request.
