### ISSUE TITLE
Временно - поддержка ХР (собрано в VC+ 2010), текущая версия для Far3

### ISSUE THREAD

**Issue by VictorVG** [michaellukashov/Far-NetBox#188]
Специально собрано в MS VC++ 2010 чтобы гарантировать работу в ХР пока нужно:

[**FarNetBox-2.1.45_Far3_x64.7z**](https://yadi.sk/d/uG9_xNOOkMU9W)
[**FarNetBox-2.1.45_Far3_x86.7z**](https://yadi.sk/d/_hcaCs7gkMUFW)

Ну и если что, то всё вместе (бывает при обновлении архива сервер скидывает линк, тогда он меняется) [**Far3**](https://yadi.sk/d/oc1fPSIbhvvwT) . Версии файлов и даты обновления архивов указаны в [**version.txt**](https://docviewer.yandex.ru/?url=ya-disk%3A%2F%2F%2Fdisk%2FFar3%2Fversion.txt&name=version.txt&c=56b631c5a970).

**Comment by michaellukashov** [comment]
Текущая версия работает под XP и под Win2k

**Comment by VictorVG** [comment]
Отлично, я эти архивы у себя уже пару часов как удалил, а про это место забыл. Спасибо!
