### ISSUE TITLE
AV в XP SP2 при старте NetBox v2.1.45.424 собранного в VC2010

### ISSUE THREAD

**Issue by VictorVG** [michaellukashov/Far-NetBox#189]
С [**forum.ru-board.com**](http://forum.ru-board.com/topic.cgi?forum=5&topic=48136&start=460#17)
> **Alexyz21**
> 
> **VictorVG2**, VC2010 при старте фара 
> 
> VC2010 при старте фара
> 
> > Exception:   Access violation (write to 0x00000019)
> > Address:     0x7C809784
> > Function:    ProcessPanelInputW
> > Module:      C:\Program Files\FAR\Plugins\NetBox\NetBox

Под Win7 SP1 x64 не воспроизводится. Может снова БД конфигов дурят?

**Comment by michaellukashov** [comment]
Исправил в 4f09a254
В завтрашней ночной сборке будет.

**Comment by VictorVG** [comment]
**michaellukashov**

Договорились, а я сейчас гляну и если сам спать не завалюсь:) в 2010-й соберу.

**Comment by VictorVG** [comment]
У нас уже лежит VC2010 сборка v2.1.45.425 32 и 64 бит. Я положил и проверил.

**Comment by VictorVG** [comment]
> **Alexyz21**
> 
> Сегодняшний официальный NB в ЯД заходит нормально

а там у нас та же версия 2.1.45.425, значит исправление подтверждено, закрываем.
