### ISSUE TITLE
v2.2.0.427 - .lng перепутан как минимум в нескольких местах

### ISSUE THREAD

**Issue by VictorVG** [michaellukashov/Far-NetBox#191]
С ходу обнаружил пару таких мест: _Queue   (Alt-Shift-Q)_ перепутан (местами?) с _Synchronize browsing   (Ctrl-Alt-B)_ ,  _Server and protocol information_ перепутан с (местами?) с диалогом настроек NetBox. Проявляется это в том, что нажимаешь на эти пункты а зовутся другие, но по хоткеям зовутся нужные...

_P.S_

_Я сейчас спать - сил нет, после ещё гляну, но по моему стоит поставить этой версии статус Бета пока с языками порядок не наведём. Это даст нам толику времени чтобы навести в LNG хоть относительный порядок_

**Comment by VictorVG** [comment]
Посмотрел на тестовой куче с чистым профилем - воспроизводится, значит да, нужно исправлять...

**Comment by michaellukashov** [comment]
Скачал последний дистрибутив фар с официального сайта, проверил - путаницы не обнаружил. Вы точно .lng файлы обновили?

**Comment by VictorVG** [comment]
Да, и сравнил с тем что с гита пришло - по SHA-256 совпадают. Может при сборке 2010-я какой сбой породила?

**Comment by michaellukashov** [comment]
Выложите где-нибудь дистрибутив - посмотрю что к чему

**Comment by VictorVG** [comment]
Посмотрел на вытащенной из ночнушки копии - то самое:

![nb](https://cloud.githubusercontent.com/assets/906886/13033411/677a8512-d326-11e5-9ed6-cd16960da593.png)

 - даём команду просмотра очереди а попадаем в меню синхронизированного просмотра:

![nb_quie](https://cloud.githubusercontent.com/assets/906886/13033420/b70f92c0-d326-11e5-840a-a7079c07c65d.png)

следом как и ожидается в логике синхронизации попадаем в диалог её настройки:

![nb_quie_next](https://cloud.githubusercontent.com/assets/906886/13033427/e007cef4-d326-11e5-866f-06bbcb4b2df6.png)

а очередь передачи не видим, но по _AltShiftQ_ её диалог вызовется сразу.

Вторая странность: режим фоновой передачи - если я не отмечу оба чекбокса _[] Передач в фоне_ и _[] Без запросов_ 

![nb_bakgnd](https://cloud.githubusercontent.com/assets/906886/13033460/b51526dc-d327-11e5-8fad-a71a6173b38e.png)

задание выполняется в режиме переднего плана

![backgraund](https://cloud.githubusercontent.com/assets/906886/13033461/bc933890-d327-11e5-990b-d625b271afcb.png)

хотя я жду фоновую передачу. 

Данных явлений на версии 2.1.45.426 у меня нет и я пока не понимаю где искать и как устранить их причину....

**Comment by VictorVG** [comment]
Не вопрос [**Far-3.0.4548-x64-test.7z**](http://www103.zippyshare.com/v/f0EookAA/file.html
) - это тест-куча. Запуск или через батник runfar.cmd из под другой копии Far (запустит в новой консоли), или при сбое профиля через recover.cmd, либо из оболочки через ./Far/Far.exe. Профиль локальный, так что рабочую копию не перезапишет.

**Comment by michaellukashov** [comment]
ok, кажется нашел в чем причина - файлы NetBoxRus.lng NetBoxEng.lng были рассинхронизированы. Выложил изменения, проверьте плиз. И спасибо.

**Comment by VictorVG** [comment]
Сейчас увидим. Гит обновлю и сможем сверить. По результатам отчитаюсь.

**Comment by VictorVG** [comment]
Версия 2.2.1.428 - тут все работает точно так же как и в версии 2.1.45.426. Можем спокойно закрывать данный инц - ошибка устранена.

**P.S.**

_Судя по тому, что у нас получилось первичная гипотеза о причине ошибка подтвердилась - путаница в .LNG файлах._

**Comment by VictorVG** [comment]
Собрал в VC++2010 и выложил на ЯндексДиск:

[**FarNetBox-2.2.1_Far3_x64.7z**](https://yadi.sk/d/9Ltnq5C7opMC2)
[**FarNetBox-2.2.1_Far3_x86.7z**](https://yadi.sk/d/mPtM2kbNopMHp)

**Comment by VictorVG** [comment]
Угу. Просто я тебя ждал чтобы и ты прочитал.
