### ISSUE TITLE
Что-то у меня 2.4.2.442 не собирается ни в 2010, ни в 2015

### ISSUE THREAD

**Issue by VictorVG** [michaellukashov/Far-NetBox#216]
После обновления до .442 пошли проблемы в виде десятков варнингов и ошибок сборки. Итогом сбой. Исходники клонировал заново, но варнинги начинают сыпаться уже на стадии сборки OpenSSL, далее просто сбой сборки. Причём не важно где - в 2010/2015 - итог один. Потому прошу помощи. Собрал все логи компилятора в один архив по платформам

[build_log.zip](https://github.com/michaellukashov/Far-NetBox/files/638337/build_log.zip)

и самое обидное никаких идей на этот счёт нет.... :(

**Comment by michaellukashov** [comment]
Сегодняшняя ночная сборка Far прошла успешно. Так что исходники в порядке. Сейчас погляжу логи, может что и прояснится.

**Comment by VictorVG** [comment]
Я думаю, что проблема у меня, но найти причину и устранить её не смог. :(

**Comment by michaellukashov** [comment]
Предполагаю, что у вас в рабочей копии выгружены исходники по тегу v2.4.2-far3
Попробуйте взять самые последние исходники из ветки far3:
git checkout far3
git pull

**Comment by VictorVG** [comment]
Выполнил с результатом:

$ git checkout far3&&git pull
M       libs/openssl/crypto/buildinf.h
Already on 'far3'
Your branch is up-to-date with 'origin/far3'.
Already up-to-date.

сейчас запустил сборку и поглядим что выйдет....

**Comment by VictorVG** [comment]
Что за проблемы? То канал лежит, перезапустил роутер - появился, то гит не клонирует:

git.exe clone --progress --recursive --branch far3 -v "https://github.com/michaellukashov/Far-NetBox.git" "G:\dev\Far-NetBox"

Cloning into 'G:\dev\Far-NetBox'...
fatal: Unable to find remote helper for 'https'

git завершил выполнение некорректно (код завершения 128) (78 ms @ 09.12.2016 1:37:43)

то не собирается... :?

**Comment by VictorVG** [comment]
Посмотрел а куда собственно ругается студия? Судя по расшифровке лога ошибок сюда - `./libs/atlmfc/include/atlbase.h` строки 4148 - 4169, точнее говорит что в строке 4151  `синтаксическая ошибка: отсутствие "," перед "<"` :

```
template <class ThreadAllocator = CComSimpleThreadAllocator, DWORD dwWait = INFINITE>
class CComAutoThreadModule :
	public CComModule,
	public CAtlAutoThreadModuleT<CComAutoThreadModule<ThreadAllocator,dwWait>, ThreadAllocator, dwWait>
{
public:
	CComAutoThreadModule(_In_ int nThreads = GetDefaultThreads()) :
		CAtlAutoThreadModuleT<CComAutoThreadModule<ThreadAllocator,dwWait>, ThreadAllocator, dwWait>(nThreads)
	{
	}
	HRESULT Init(
		_In_ _ATL_OBJMAP_ENTRY* p,
		_In_ HINSTANCE h,
		_In_opt_ const GUID* plibid = NULL,
		_In_ int nThreads = GetDefaultThreads())
	{
		nThreads;
		ATLASSERT(nThreads == GetDefaultThreads() && _T("Set number of threads through the constructor"));
		return CComModule::Init(p, h, plibid);
	}
};
```
и если она права, то что должно на самом деле стоять чтобы VC++2010 SP и VC++2015 Update 3 не находили в этом месте ошибок?

Собрал всё, что вывели компиляторы в общий архив (здоровый вышел, 73 Мб в зипе) [**build.zip**](http://www50.zippyshare.com/v/ppwdptXg/file.html) поскольку предполагаю что это позволит понять что происходит?

**Comment by VictorVG** [comment]
Отсмотрел что вывели компиляторы и оставил только те логи где сборка или выдала варнинги либо завершилась неудачей: [NB_2.4.2.442_build_log_vc2010_2015_problems_only.zip](https://github.com/michaellukashov/Far-NetBox/files/642482/NB_2.4.2.442_build_log_vc2010_2015_problems_only.zip)

при этом заметил что компилятор сбоит на вроде безобидное изменение промежуточного каталога сборки. По идее такого быть явно не должно. Может опять какой-то сбой локальной ОС? Я уже смотрю на неё как на гарантированный источник скрытых ошибок...

**Comment by VictorVG** [comment]
Посмотрим что выйдет после переделки сборочных скриптов (сам в их зоопарке запутался :) ) на более простой вариант [scripts.zip](https://github.com/michaellukashov/Far-NetBox/files/642591/scripts.zip) выведший такой лог гита [git.log.zip](https://github.com/michaellukashov/Far-NetBox/files/642592/git.log.zip)

**Comment by VictorVG** [comment]
Похоже первопричина в SEH модели исключений заданной ключом [**/EHsc**](https://msdn.microsoft.com/ru-ru/library/1deeycx5.aspx) компилятора - судя по всему он тут что-то путает и в итоге получаем сбой....

**Comment by VictorVG** [comment]
2015 с 3 апдейтом так же не собирает - [build_vc15_xp.zip](https://github.com/michaellukashov/Far-NetBox/files/642713/build_vc15_xp.zip) . Или я где-то напутал или в проекте что-то не нравится компилятору и он прерывает работу...

**Comment by VictorVG** [comment]
Похоже переменные среды компилятора у меня сбиты. Буду смотреть по описанию с MSDN чего у меня нет.

**Comment by VictorVG** [comment]
Поправил скрипт:

```
@echo off
@git.exe pull origin -f > git.log
@git checkout far3 >> git.log
@git pull >> git.log
@rm -fr ./build
@setlocal
@set path=%PATH%;C:\PROGRA~2\MICROS~2.0\VC\bin;C:\PROGRA~2\MICROS~2.0\Common7\IDE;
@set INCLUDE=C:\PROGRA~2\MICROS~2.0\VC\include
@set LIBPATH=.\libs
@cd libs\openssl
@call ..\..\src\NetBox\scripts\build_openssl.bat x86
@call ..\..\src\NetBox\scripts\build_openssl.bat x64
@cd /d ..\..\src\NetBox
@cmd /c "%VS100COMNTOOLS%\..\..\VC\vcvarsall.bat" x86 && devenv.exe NetBox.sln /Build "Release|Win32" /USEENV /Project "NetBox"
@cmd /c "%VS100COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64 && devenv.exe NetBox.sln /Build "Release|x64" /USEENV /Project "NetBox"
@endlocal
@cd ..\..\
@if not exist ".\build\x64\Far\Plugins\NetBox" (@mkdir "./build/x64/Far/Plugins/NetBox")
@if not exist ".\build\x86\Far\Plugins\NetBox" (@mkdir "./build/x86/Far/Plugins/NetBox")
@if not exist ".\build\NetBox\x64" (@mkdir "./build/NetBox/x64")
@if not exist ".\build\NetBox\x86" (@mkdir "./build/NetBox/x86")
@cp -f ./build/NetBox/Far3/x64/* ./build/x64/Far/Plugins/NetBox
@cp -f ./build/NetBox/Far3/x86/* ./build/x86/Far/Plugins/NetBox
@cp -f ./build/Release/x64/NetBox.map ./build/x64/Far/Plugins/NetBox
@cp -f ./build/Release/x86/NetBox.map ./build/x86/Far/Plugins/NetBox
@mv -f ./build/NetBox/Far3/x64/* ./build/NetBox/x64
@mv -f ./build/NetBox/Far3/x86/* ./build/NetBox/x86
@rm -fR ./build/NetBox/Far3 > nul
@rm -fR ./build/VC10 > nul
@rm -fR ./Build/Release > nul
@rm -fR ./Far3_x64 > nul
@rm -fR ./Far3_x86 > nul
@exit
```
ничего не выходит, логах одни варнинги и сообщения о сбое сборки:

[build.zip](https://github.com/michaellukashov/Far-NetBox/files/643838/build.zip)

**Comment by VictorVG** [comment]
Какой день пытаюсь решить проблему, но всё упирается сюда:

> 
> Построение начато 11.12.2016 18:25:05.
>      1>Проект ".\dev\Far-NetBox\libs\atlmfc\mfc.vcxproj" в узле 2 (целевые объекты build).
>      1>InitializeBuildStatus:
>          Создание "..\..\build\vc10\mfc\Release\x86\mfc\mfc.unsuccessfulbuild", так как было задано "AlwaysCreate".
>        ClCompile:
>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\CL.exe /c /Iinclude /I../../src/base /Zi /nologo /W1 /WX- /MP /O1 /Os /Oy /D WIN32 /D NDEBUG /D UNICODE /D _UNICODE /D _WIN32_WINNT=0x0501 /D _ATL_NO_DEBUG_CRT /D _ATL_NO_UUIDOF /D _ATL_NO_CONNECTION_POINTS /D _ATL_NO_DATETIME_RESOURCES_ /D _ATL_NO_DEFAULT_LIBS /D _ATL_NO_PERF_SUPPORT /D _AFX_PORTABLE /D _UNICODE /D UNICODE /GF /Gm- /EHsc /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /GR- /Fo"..\..\build\vc10\mfc\Release\x86\mfc\\" /Fd"..\..\build\vc10\mfc\Release\x86\mfc\vc100.pdb" /Gd /TP /wd4995 /wd4100 /analyze- /errorReport:prompt mfc1.cpp mfc2.cpp mfc3.cpp mfc4.cpp mfc5.cpp src\mfc\thrdcore.cpp
>          mfc1.cpp
>          mfc2.cpp
>          mfc3.cpp
>          mfc4.cpp
>          mfc5.cpp
>          thrdcore.cpp
>      1>.\dev\Far-NetBox\libs\atlmfc\include\atlbase.h(4151): error C2143: синтаксическая ошибка: отсутствие "," перед "<"
>                  .\dev\Far-NetBox\libs\atlmfc\include\atlbase.h(4168): см. ссылку на создание экземпляров класса шаблон при компиляции "ATL::CComAutoThreadModule<ThreadAllocator,dwWait>"
>      1>.\dev\Far-NetBox\libs\atlmfc\include\atlbase.h(4151): error C2143: синтаксическая ошибка: отсутствие "," перед "<"
>                  .\dev\Far-NetBox\libs\atlmfc\include\atlbase.h(4168): см. ссылку на создание экземпляров класса шаблон при компиляции "ATL::CComAutoThreadModule<ThreadAllocator,dwWait>"
>      1>.\dev\Far-NetBox\libs\atlmfc\include\atlbase.h(4151): error C2143: синтаксическая ошибка: отсутствие "," перед "<"
>                  .\dev\Far-NetBox\libs\atlmfc\include\atlbase.h(4168): см. ссылку на создание экземпляров класса шаблон при компиляции "ATL::CComAutoThreadModule<ThreadAllocator,dwWait>"
>      1>.\dev\Far-NetBox\libs\atlmfc\include\atlbase.h(4151): error C2143: синтаксическая ошибка: отсутствие "," перед "<"
>                  .\dev\Far-NetBox\libs\atlmfc\include\atlbase.h(4168): см. ссылку на создание экземпляров класса шаблон при компиляции "ATL::CComAutoThreadModule<ThreadAllocator,dwWait>"
>      1>.\dev\Far-NetBox\libs\atlmfc\include\atlbase.h(4151): error C2143: синтаксическая ошибка: отсутствие "," перед "<"
>                  .\dev\Far-NetBox\libs\atlmfc\include\atlbase.h(4168): см. ссылку на создание экземпляров класса шаблон при компиляции "ATL::CComAutoThreadModule<ThreadAllocator,dwWait>"
>      1>Построение проекта ".\dev\Far-NetBox\libs\atlmfc\mfc.vcxproj" завершено (целевые объекты build) с ошибкой.
> 
> СБОЙ построения.
> 
> Затраченное время: 00:00:01.15

и никаких идей нет...

**Comment by michaellukashov** [comment]
Я разобрался, ошибка была в конфигурации Release|Win32 и проявлялась при сборке с помощью .sln файла для VisualStudio. Обновите пожалуйста исходники, сейчас сборка должна исправиться

**Comment by VictorVG** [comment]
Сейчас сделаем. И я вчера сделал полезное для нас - сравнил секции импорта двух сборок - 2010-й .441 и 2015-й .442. Вот в .441 x64 точно были четыре функции для Висты с именами FlsAlloc, FlsFree, FlsGetValue и FlsSetValue - я это по MSDN проверял. В .442 новых функций появившихся после Windows XP нет - тут 2015-й компилятор  сработал корректно.

**Comment by VictorVG** [comment]
Да, из IDE 2010 собирается, а с батниками придётся повозится - на них не выходит.:( 

И вот поимённая разница вызовов вставляемых VC2010 SP1 vs VC2015 (на сервере):

[x64.txt](https://github.com/michaellukashov/Far-NetBox/files/646323/x64.txt)
[x86.txt](https://github.com/michaellukashov/Far-NetBox/files/646322/x86.txt)

VC2015 вставляет около 90 вызовов, VC2010 до 19, зато наши "знакомые" в х64 сборке присутствуют все - FlsAlloc, FlsFree, FlsGetValue и FlsSetValue .

**Comment by VictorVG** [comment]
Собрал из ИДЕ, а в скрипте видать напутал ибо этот вариант уходит в нирвану начиная собирать сам NetBox:

@echo off
@git.exe pull origin -f > git.log
@git checkout far3 >> git.log
@git pull >> git.log
@rm -fr ./build
@rm -fr ./build ./Far3_x64 ./Far3_x86
@cd ./libs/openssl
@call ../../src/NetBox/scripts/build_openssl.bat x86
@call ../../src/NetBox/scripts/build_openssl.bat x64
@cd ../../
@cd /d .\src\NetBox
@cmd /c "%VS100COMNTOOLS%\..\..\VC\vcvarsall.bat" x86 && "%VS100COMNTOOLS%\..\IDE\devenv.exe" NetBox2010.sln /Build "Release|Win32" /USEENV /Project "NetBox"
@cmd /c "%VS100COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64 && "%VS100COMNTOOLS%\..\IDE\devenv.exe" NetBox2010.sln /Build "Release|x64" /USEENV /Project "NetBox"
@cd /d ../../
@if not exist ".\build\x64\Far\Plugins\NetBox" (@mkdir "./build/x64/Far/Plugins/NetBox")
@if not exist ".\build\x86\Far\Plugins\NetBox" (@mkdir "./build/x86/Far/Plugins/NetBox")
@if not exist ".\build\NetBox\x64" (@mkdir "./build/NetBox/x64")
@if not exist ".\build\NetBox\x86" (@mkdir "./build/NetBox/x86")
@rm -f ./Far3_x64/Plugins/NetBox/*.lib ./Far3_x64/Plugins/NetBox/*.exp ./Far3_x86/Plugins/NetBox/*.lib ./Far3_x86/Plugins/NetBox/*.exp
@cp -f ./src/NetBox/*.lng ./Far3_x64/Plugins/NetBox
@cp -f ./src/NetBox/*.lng ./Far3_x86/Plugins/NetBox
@cp -f ./*.md ./Far3_x64/Plugins/NetBox
@cp -f ./*.md ./Far3_x86/Plugins/NetBox
@cp -f ./ChangeLog ./Far3_x64/Plugins/NetBox
@cp -f ./ChangeLog ./Far3_x86/Plugins/NetBox
@cp -f ./LICENSE.txt ./Far3_x64/Plugins/NetBox
@cp -f ./LICENSE.txt ./Far3_x86/Plugins/NetBox
@cp -f ./Far3_x64/Plugins/NetBox/* ./build/x64/Far/Plugins/NetBox
@cp -f ./Far3_x86/Plugins/NetBox/* ./build/x86/Far/Plugins/NetBox
@cp -f ./Far3_x86/Plugins/NetBox/* ./build/NetBox/x86
@cp -f ./Far3_x64/Plugins/NetBox/* ./build/NetBox/x64
@rm -fR ./build/NetBox/x64/*.map  ./build/NetBox/x86/*.map > nul
@rm -fR ./build/NetBox/Far3 > nul
@rm -fR ./build/VC10 > nul
@rm -fR ./Build/Release > nul
@rm -fR ./Far3_x64 > nul
@rm -fR ./Far3_x86 > nul
@exit

дальше ошибиться негде и этот блок работает - Msys/CygWin найти не долго, а в демоне cp/mv/rn штатные.
