### ISSUE TITLE
Git-598f5bc02f : проблемы сборки - VC2010 сбой на libneon, у VC2015 куча варнингов...

### ISSUE THREAD

**Issue by VictorVG** [michaellukashov/Far-NetBox#221]
В Git-598f5bc02f пришла свежая пачка проблем: 

Первая это вопрос: либы SSL вроде и собрались, но в конце сборки вместо привычного openssl.exe:1 сообщения перла - тут нет нужды обновлять перл с 5.24?

А вот при сборке в VC2010 последовательность сбоев - сначала не собирается libneon, после и сам NetBox. Логи в Zip;

[**vc10_build_filure_log.zip**](https://github.com/michaellukashov/Far-NetBox/files/737061/vc10_build_filure_log.zip)

не собираются обе конфигурации и 32 и 64 бита в релизе.

В VC14 собирается, только сразу вылезает факт что он собирает минимум для Vista ставя в хидере DLL поля:

x86 и х64:

  _required OS version           6.00
  subsystem version             6.00_

и по идее старые ОС такой плагин не запустят. Собственно из-за них мне и приходится собирать в VC2010 - люди просят так по их словам у них VC14 сборки на ХР не запускаются.

Вот логи сборки [**vc15_build_warning_log.zip**](https://github.com/michaellukashov/Far-NetBox/files/737063/vc15_build_warning_log.zip) и собранный плагин им [**NetBox_VC14_build.zip**](https://github.com/michaellukashov/Far-NetBox/files/737064/NetBox_VC14_build.zip). Собранный в VC2010 собирался для ХР и выше:

х86:

  _required OS version           5.01
  subsystem version             5.01_

x64:

  _required OS version           5.02
  subsystem version             5.02_

**Comment by michaellukashov** [comment]
openSSL теперь не нужно пересобирать вручную с помощью build_openssl.bat - я закоммитил собранные .lib файлы, для удобства.
После пересборки openssl с помощью build_openssl.bat нужно заново закоммитить ревизию 0dbd070dffd7 (openssl custom header patches), это нужно для сборки neon.

**Comment by VictorVG** [comment]
@michaellukashov

Доброе дело. Всяко проще нам будет. А у глянул как у меня новая версия с роутером себя ведёт - к ZyXEL Keenetic Extra с прошивкой v2.07 (AANS.5) C3 на котором поднят pure-ftpd подключается мгновенно, сброс данных 13,8 - 15 Мб/с - это технический предел 2,5" USB 2.0 HDD на 5400 rpm. 

Быстрее эти диски только на IEEE-1394a в Sarotec-й коробке работают, и то коли на машине стоит чит от Texas Instrument. Если VIA VT6307 - быстрее 18 - 19 Мб/с не чип не пропустит, да и контроллеры на VT630x горят как семечки т.к. заводы часто экономят на схеме включения, а эти чипы этого сильно не любят - из десятка бюджетных плат редко какая проработает более года - но просто так у большинства заводов на них срок гарантии не превышает 9 - 10 месяцев.:)

С внешними FTP - FreeBSD.org, [**TDF**](ftp://anonymous:@ftp5.gwdg.de:21/pub/) (зеркало ряда проектов, в т.ч. LibreOffice, архив RFC и ещё многое что может нам пригодится) так же время подключения минимальное. Субъективно меньше чем с OpenSSL 1.0.x.

**Comment by VictorVG** [comment]
Ну, по прочтению можем и закрыть собралось, правда батник:

```
@echo off
@rm -fr ./build
rem @cd ./libs/openssl
rem @call ../../src/NetBox/scripts/build_openssl.bat x86
rem @call ../../src/NetBox/scripts/build_openssl.bat x64
@cd /d ../../src/NetBox
@cmd /c "%VS100COMNTOOLS%\..\..\VC\vcvarsall.bat" x86 && "%VS100COMNTOOLS%\..\IDE\devenv.exe" NetBox.sln /Build "Release|Win32" /USEENV /Project "NetBox"
cmd /c "%VS100COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64 && "%VS100COMNTOOLS%\..\IDE\devenv.exe" NetBox.sln /Build "Release|x64" /USEENV /Project "NetBox"
@cd /d ../../
@nboxrls.cmd
@exit
EOF:
```
не хочет работать и приходится иде звать.:( второй просто соббирает всё в одно место с чисткой от лишних файлов, а этот проскакивает стадию сборки...

**Comment by VictorVG** [comment]
Сборку на скриптах починил, но пришлось с ней повозится.:)

**Comment by VictorVG** [comment]
Сборочных проблем с таким набором скриптов [**Far-NetBox_bldtoold.zip**](https://github.com/michaellukashov/Far-NetBox/files/738013/Far-NetBox_bldtoold.zip) нет. Обвеска - perl 5.24, git 2.11.0, CMake 3.7.2, Msys 1.0.17 с комплектом UNIX утилит cp, md, mv, rm, tar, xz b 7-Zip. Компилятор VC++2010.

Прикрываем?
