### ISSUE TITLE
Не распознаётся SCP от Win32-OpenSSH

### ISSUE THREAD

**Issue by rustyx** [michaellukashov/Far-NetBox#222]
Не работает SCP с сервером от Майкрософтовского порта OpenSSH:
https://github.com/PowerShell/Win32-OpenSSH
(Подробности установки [тут](https://winscp.net/eng/docs/guide_windows_openssh_server))
Даже на localhost:
`Error skipping startup message. Your shell is probably incompatible with the application (BASH is recommended).`

**Comment by VictorVG** [comment]
Интересно, а кто и как сможет сказать что у вас не работает без логов? Микрософт конечно как всегда "_мы единственные делаем правильно_", но среди нас простите телепатов нет, а последний местный телепат вышел на пенсию ещё во времена динозавров...

**Comment by rustyx** [comment]
Как выяснилось ошибка повторима в winscp, так что я открыл баг там:
https://winscp.net/forum/viewtopic.php?t=24499

**Comment by VictorVG** [comment]
Ну, там вроде попонятнее с чем вы столкнулись. Что до мелкомягких серверов так они и свой гит написали "_У нас столь кривые сервера что нам проще объявить их прямыми, чем свою халтуру исправить!_".:)
