### ISSUE TITLE
Убрать префикс netbox: в заголовке

### ISSUE THREAD

**Issue by 2underscores-vic** [michaellukashov/Far-NetBox#229]
v. 2.4.2 build 472

В заголовке окна Far появился префикс `netbox:...`. Из-за этого конкретное имя сессии в панели задач теперь не влезает. Как его убрать?

**Comment by VictorVG** [comment]
Например Crl-Left|Ctrl-Right или открыть окно на полный экран.

**Comment by 2underscores-vic** [comment]
Чего? Как это повлияет на виндовую панель задач?

**Comment by VictorVG** [comment]
А я так вас понял что в панели фар читать трудно -  там же то же выводится. А на ось я в этом углу и внимание не обратил.

**Comment by 2underscores-vic** [comment]
Когда запущено несколько экземпляров с SCP в NetBox, то на панели задач из-за префикса их одним взглядом не различить. 7 ненужных символов занимают очень полезное место.
`Far - {путь}` в заголовке окна не зря заменили на `{путь} - Far` в своё время.

Прошу убрать префикс или сделать его отключаемым, если кому-то он очень дорог.

**Comment by 2underscores-vic** [comment]
v. 2.4.3 build 492 - префикс пропал.
Спасибо!
