### ISSUE TITLE
FIXED:  v2.4.3.483 в VC2010 - не собирается libputty и в итоге сбой построения, а собранная в VC2015 при наличии запущенного плагина Drag-n-Drop на старте падает роняя Far.

### ISSUE THREAD

**Issue by VictorVG** [michaellukashov/Far-NetBox#230]
Лог грепа:

[1] .\x64\NetBox.log
     1>Построение проекта ".\src\NetBox\NetBox.vcxproj" завершено (целевые объекты build) с ошибкой.

[2] .\x64\libputty\libputty.log
     1>Построение проекта ".\libs\Putty\libputty.vcxproj" завершено (целевые объекты build) с ошибкой.

[3] .\x86\NetBox.log
     1>Построение проекта ".\src\NetBox\NetBox.vcxproj" завершено (целевые объекты build) с ошибкой.

[4] .\x86\libputty\libputty.log
     1>Построение проекта ".\libs\Putty\libputty.vcxproj" завершено (целевые объекты build) с ошибкой.

В то же время в VC2015 собирается, но минимум для Vista, а судя по проекту используется SDK по Win10 10586...

Логи сборки прикрепил - [**vc10.zip**](https://github.com/michaellukashov/Far-NetBox/files/950741/vc10.zip). Может есть смысл и эту либу в готовом виде добавить чтобы избежать проблем?

**Comment by VictorVG** [comment]
Тут вспомнил что были проблемы с CMake, а у меня сейчас стоит 3.80 и откатить не смогу - другие программы не соберутся так как они все на неё через сборочный сервер завязаны.

**Comment by VictorVG** [comment]
Только что словил на семёрке:

  Имя приложения:	Far.exe
  Версия приложения:	3.0.4941.0
  Отметка времени приложения:	58fd8e3c
  Имя модуля с ошибкой:	NetBox.dll
  Версия модуля с ошибкой:	2.4.3.483
  Отметка времени модуля с ошибкой:	58fda539
  Код исключения:	40000015
  Смещение исключения:	0000000000245f9f
  Версия ОС:	6.1.7601.2.1.0.256.1
  Код языка:	1049
  
сейчас с PDB соберу поглядим где собака порылась?

**Comment by VictorVG** [comment]
При наличии в системе запущенного в любой копии Far плагина Drag-n-Drop v3.0.0.82 NetBox v2.4.3.483 падает при старте Far с сообщением в отладчике "[i]Ссылка на объект не указывает на экземпляр объекта.[/i]". При использовании D&D v3.0.0.81 падение происходит при запуске NetBox v2.4.3.483. Версия 2.4.2.475 работает без ошибок с любой версией D&D.

**Comment by VictorVG** [comment]
Проверил и с вариантом из ночнушки с сервера - воспроизводится 100%.  Для D&D v3.0.081 достаточно просто открыть панель NetBox, если запущен D&D v3.0.0.82 падает при запуске Far.

**Comment by VictorVG** [comment]
Ошибка сидела в NetBox-е ибо версия 2.4,3,483 собранная из Git - 7c58c40bb0a74570f9e уже с D&D не падает.

**Comment by VictorVG** [comment]
Заодно вопрос вылез - в .\src\NetBox\NetBox.vcxproj строки 27 - 28 и 37 - 38 содержат:

```
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '14.0'">v140</PlatformToolset>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '15.0'">v141</PlatformToolset>
```

по идее, если на сборочной машине нет этих тулкитов это должно вызвать молчаливое завершение с кодом выхода cl == 2. Что я исправно наблюдаю. В vc2010 или это не нужно и NB сможет работать на ХР? У меня не на чем это проверить. :(

**Comment by VictorVG** [comment]
Если запущен плагин Drag-n-Drop то NetBox v2.4.3.483 собранный в VC2015/2017 падает при вызове  с кодом ошибки 0х40000015. Сборка NetBox v2.4.3.483 Git-7c58c40bb0a74570f9e из VC2010 IDE не падает, а сборка в VC2015 по прежнему падает с той же ошибкой судя по запуску с подсунутой PDB в CRT тут:

![1](https://cloud.githubusercontent.com/assets/906886/25377736/047c3784-29b1-11e7-837c-65c74eb2e3a2.png)

**Comment by VictorVG** [comment]
И ещё одно замечено - сбой вызывается при наличии в профиле БД [42E4AEB1-A230-44F4-B33C-F195BB654931.db.zip](https://github.com/michaellukashov/Far-NetBox/files/954656/42E4AEB1-A230-44F4-B33C-F195BB654931.db.zip) сохранённой в предыдущих версиях NB т.к. если провести такой эксперимент:

1) экспортируем (бэкапим) сессии в версии 2.4.2.475, а затем удаляем саму БД:
2) обновляем NB до v2.4.3.483, причём берём вариант собранный в VC14/VC15 ибо падают только они!
3) запускаем Far и зовём NetBox;
4) восстанавливаем сессии из бэкапа импортируя их в плагин;
5) вызываем любую сессию - падения не возникает, если это не сделать - падаем с кодом исключения 0х40000015.

**Comment by grechnik** [comment]
http://stackoverflow.com/questions/280477/crt-debugger-hook-throws-exception - пишут, что такое падение бывает, если разные зависимости компилировались в разных версиях VS или в разных режимах debug/release.

**Comment by VictorVG** [comment]
А кстати возможно и это, сейчас заодно посмотрю  как себя поведёт Far SVN r14883 - там **zg** исправил ошибку:

> **zg** 25.04.2017 12:59:57 +0200 - build 4943
> 
> 1. исключение при вызове mf.fsplit('a.:',0x4+0x8)

самое плохое что не удаётся отловить состояние задачи в момент  падения т.к. ОС молча вызывает TerminateProcess() до того, как выводит сообщение о падении, а дампах [**CrashDumps.zip**](https://github.com/michaellukashov/Far-NetBox/files/954862/CrashDumps.zip) только системные библиотеки видны...

**Comment by grechnik** [comment]
А собранный бинарник+pdb можно посмотреть?

**Comment by VictorVG** [comment]
Без вопросов, и я сейчас глянул в b4943 + NB 2.4.3.483 собранный в VC14 - при его вызове с той же старой БД сразу падает:

![1](https://cloud.githubusercontent.com/assets/906886/25384619/ac1e1346-29c9-11e7-91e0-5b6597cb8e48.png)

нажимаем в отладчике 2015-й F5 и видим:

![2](https://cloud.githubusercontent.com/assets/906886/25384638/c4887ae8-29c9-11e7-81f1-86e226231ae9.png)

Бинарники и сборочный скрипт:

[**VC2010.7z**](https://yadi.sk/d/WZSkjJlF3HLKa5) - собран в IDE (скриптом не собирается)
[**VC2015.7z**](https://yadi.sk/d/_foXTWNl3HLKbj) - собран системой скриптов


```
@echo off
@setlocal
@set ROOTDIR=%~dp0
@rem Don't chage %PROJECT_ROOT%!
rem Script adaptive configuration
rem VS2010 block begin, is default. Needed comment for use VS2015
rem @set VSVER=2010
rem @set VCVSRS="%VS100COMNTOOLS%..\..\VC\vcvarsall.bat"
rem @set VCC=VC10
rem VS2010 block end
rem VS2015 block begin. Uncoment if needed
@set VSVER=2015
@set VCVSRS="%VS140COMNTOOLS%..\..\VC\vcvarsall.bat"
@set VCC=VC14
rem VS2015 block end
rem
@set BLDDIR=%ROOTDIR%build
@set PKGDIR=%BLDDIR%\NetBox\Far3
@set PLGDIR=%BLDDIR%\NetBox
@set BIN=Far\Plugins\NetBox
@set PROJECT_KIT=vs%VSVER%
@git.exe pull origin -f
@git checkout far3
@git pull
@rm -fr ./build ./Far3_x64./Far3_x86 > NUL
@set PROJECT_GENERATOR=NMake Makefiles
@set FAR_VERSION=Far3
@set PROJECT_BUILD_TYPE=Release
@set PROJECT_BUIILDDIR=%ROOTDIR%build\%PROJECT_KIT%\%PROJECT_BUILD_TYPE%\x86
@if not exist %PROJECT_BUIILDDIR% ( md %PROJECT_BUIILDDIR% > NUL )
@cd /d %PROJECT_BUIILDDIR%
@call %VCVSRS% x86
@cmake.exe -D PROJECT_ROOT=%ROOTDIR% -D CMAKE_BUILD_TYPE=%PROJECT_BUILD_TYPE% -G "%PROJECT_GENERATOR%" -D FAR_VERSION=Far3 %ROOTDIR%src\NetBox
@nmake
@cd /d ..\..\..\
@set PROJECT_BUIILDDIR=%ROOTDIR%build\%PROJECT_KIT%\%PROJECT_BUILD_TYPE%\x64
@if not exist %PROJECT_BUIILDDIR% ( md %PROJECT_BUIILDDIR% > NUL )
@cd /d %PROJECT_BUIILDDIR%
@call %VCVSRS% x86_amd64
@cmake.exe -D PROJECT_ROOT=%ROOTDIR% -D CMAKE_BUILD_TYPE=%PROJECT_BUILD_TYPE% -G "%PROJECT_GENERATOR%" -D FAR_VERSION=Far3 %ROOTDIR%src\NetBox
@nmake
@endlocal
@cd /d %~dp0
@setlocal
@set PLUGINNAME=NetBox
@set FARVER=Far3
@set BLDDIR=..\..\..\build
@set PKGDIR=%BLDDIR%\%PLUGINNAME%\%FARVER%
@set PLGDIR=%BLDDIR%\%PLUGINNAME%
@set BIN=Far\Plugins\%PLUGINNAME%
@set VSVER=2015
@if not exist ".\build\x64\Far\Plugins\NetBox" (@mkdir "./build/x64/Far/Plugins/NetBox")
@if not exist ".\build\x86\Far\Plugins\NetBox" (@mkdir "./build/x86/Far/Plugins/NetBox")
@if not exist ".\build\NetBox\x64" (@mkdir "./build/NetBox/x64")
@if not exist ".\build\NetBox\x86" (@mkdir "./build/NetBox/x86")
@rm -f ./Far3_x64/Plugins/NetBox/*.lib ./Far3_x64/Plugins/NetBox/*.exp ./Far3_x86/Plugins/NetBox/*.lib ./Far3_x86/Plugins/NetBox/*.exp
@cp -f ./src/NetBox/*.lng ./Far3_x64/Plugins/NetBox
@cp -f ./src/NetBox/*.lng ./Far3_x86/Plugins/NetBox
@cp -f ./*.md ./Far3_x64/Plugins/NetBox
@cp -f ./*.md ./Far3_x86/Plugins/NetBox
@cp -f ./ChangeLog ./Far3_x64/Plugins/NetBox
@cp -f ./ChangeLog ./Far3_x86/Plugins/NetBox
@cp -f ./LICENSE.txt ./Far3_x64/Plugins/NetBox
@cp -f ./LICENSE.txt ./Far3_x86/Plugins/NetBox
@cp -f ./Far3_x64/Plugins/NetBox/* ./build/x64/Far/Plugins/NetBox
@cp -f ./Far3_x86/Plugins/NetBox/* ./build/x86/Far/Plugins/NetBox
@cp -f ./Far3_x86/Plugins/NetBox/* ./build/NetBox/x86
@cp -f ./Far3_x64/Plugins/NetBox/* ./build/NetBox/x64
@cd /d src\NetBox\scripts
@gawk "/PLUGIN_VERSION_TXT/ {print $3}" ../resource.h > version.tmp
@for /F %%i in (version.tmp) do set PLUGINVER=%%i
@gawk "/NETBOX_VERSION_BUILD/ {print $3}" ../plugin_version.hpp > version.tmp
@for /F %%i in (version.tmp) do set PLUGREV=%%i
@rm -f version.tmp
@set PKGNAME=Far%PLUGINNAME%-%PLUGINVER%.%PLUGREV%_%FARVER%
@set RLSDIR=%BLDDIR%\vs%VSVER%\Release
@if not exist %PKGDIR% mkdir %PKGDIR% > NUL
@if exist %PKGDIR%\x64 rmdir /S /Q %PKGDIR%\x64 > NUL
@mkdir %PKGDIR%\x64 > NUL
@if not exist %BLDDIR%\x64\%BIN% mkdir %BLDDIR%\x64\%BIN% > nul
@copy /b /y %PLGDIR%\x64\* %PKGDIR%\x64 > NUL
@copy /b /y %RLSDIR%\x64\%PLUGINNAME%.map %PKGDIR%\x64 > NUL
@copy /b /y %PLGDIR%\x64\* %BLDDIR%\x64\%BIN%> NUL
@copy /b /y %RLSDIR%\x64\%PLUGINNAME%.map %BLDDIR%\x64\%BIN% > NUL
@call "C:\Program Files\7-Zip\7z.exe" a -mx9 -t7z -r %BLDDIR%\%PKGNAME%_x64.7z %PKGDIR%\x64\* > NUL
@if exist %PKGDIR%\x86 rmdir /S /Q %PKGDIR%\x86 > NUL
@mkdir %PKGDIR%\x86 > NUL
@if not exist %BLDDIR%\x86\%BIN% mkdir %BLDDIR%\x86\%BIN% > nul
@copy /b /y %PLGDIR%\x86\* %PKGDIR%\x86 > NUL
@copy /b /y %RLSDIR%\x86\%PLUGINNAME%.map %PKGDIR%\x86 > NUL
@copy /b /y %PLGDIR%\x86\* %BLDDIR%\x86\%BIN%> NUL
@copy /b /y %RLSDIR%\x86\%PLUGINNAME%.map %BLDDIR%\x86\%BIN% > NUL
@call "C:\Program Files\7-Zip\7z.exe" a -mx9 -t7z -r %BLDDIR%\%PKGNAME%_x86.7z %PKGDIR%\x86\* > NUL
@rmdir /S /Q %PKGDIR%
@cd /d ..\..\..\
@rm -fR ./build/NetBox/x64/*.map  ./build/NetBox/x86/*.map > nul
@rm -fR ./build/NetBox/Far3 > nul
@rm -fR ./build/VC10  ./build/VC14 > nul
@rm -fR ./Build/Release > nul
@rm -fR ./Far3_x64 > nul
@rm -fR ./Far3_x86 > nul
@rm -fR ./build/vs2010 ./build/vs2015> nul
@exit
```
для 2010 в скрипт вносятся минимальные изменения:

```
@echo off
@setlocal
@set ROOTDIR=%~dp0
@rem Don't chage %PROJECT_ROOT%!
rem Script adaptive configuration
rem VS2010 block begin, is default. Needed comment for use VS2015
@set VSVER=2010
@set VCVSRS="%VS100COMNTOOLS%..\..\VC\vcvarsall.bat"
@set VCC=VC10
rem VS2010 block end
rem VS2015 block begin. Uncoment if needed
rem @set VSVER=2015
rem @set VCVSRS="%VS140COMNTOOLS%..\..\VC\vcvarsall.bat"
rem @set VCC=VC14
rem VS2015 block end
rem
@set BLDDIR=%ROOTDIR%build
@set PKGDIR=%BLDDIR%\NetBox\Far3
@set PLGDIR=%BLDDIR%\NetBox
@set BIN=Far\Plugins\NetBox
@set PROJECT_KIT=vs%VSVER%
@git.exe pull origin -f
@git checkout far3
@git pull
@rm -fr ./build ./Far3_x64./Far3_x86 > NUL
@set PROJECT_GENERATOR=NMake Makefiles
@set FAR_VERSION=Far3
@set PROJECT_BUILD_TYPE=Release
@set PROJECT_BUIILDDIR=%ROOTDIR%build\%PROJECT_KIT%\%PROJECT_BUILD_TYPE%\x86
@if not exist %PROJECT_BUIILDDIR% ( md %PROJECT_BUIILDDIR% > NUL )
@cd /d %PROJECT_BUIILDDIR%
@call %VCVSRS% x86
@cmake.exe -D PROJECT_ROOT=%ROOTDIR% -D CMAKE_BUILD_TYPE=%PROJECT_BUILD_TYPE% -G "%PROJECT_GENERATOR%" -D FAR_VERSION=Far3 %ROOTDIR%src\NetBox
@nmake
@cd /d ..\..\..\
@set PROJECT_BUIILDDIR=%ROOTDIR%build\%PROJECT_KIT%\%PROJECT_BUILD_TYPE%\x64
@if not exist %PROJECT_BUIILDDIR% ( md %PROJECT_BUIILDDIR% > NUL )
@cd /d %PROJECT_BUIILDDIR%
@call %VCVSRS% x86_amd64
@cmake.exe -D PROJECT_ROOT=%ROOTDIR% -D CMAKE_BUILD_TYPE=%PROJECT_BUILD_TYPE% -G "%PROJECT_GENERATOR%" -D FAR_VERSION=Far3 %ROOTDIR%src\NetBox
@nmake
@endlocal
@cd /d %~dp0
@setlocal
@set PLUGINNAME=NetBox
@set FARVER=Far3
@set BLDDIR=..\..\..\build
@set PKGDIR=%BLDDIR%\%PLUGINNAME%\%FARVER%
@set PLGDIR=%BLDDIR%\%PLUGINNAME%
@set BIN=Far\Plugins\%PLUGINNAME%
@set VSVER=2010
@if not exist ".\build\x64\Far\Plugins\NetBox" (@mkdir "./build/x64/Far/Plugins/NetBox")
@if not exist ".\build\x86\Far\Plugins\NetBox" (@mkdir "./build/x86/Far/Plugins/NetBox")
@if not exist ".\build\NetBox\x64" (@mkdir "./build/NetBox/x64")
@if not exist ".\build\NetBox\x86" (@mkdir "./build/NetBox/x86")
@rm -f ./Far3_x64/Plugins/NetBox/*.lib ./Far3_x64/Plugins/NetBox/*.exp ./Far3_x86/Plugins/NetBox/*.lib ./Far3_x86/Plugins/NetBox/*.exp
@cp -f ./src/NetBox/*.lng ./Far3_x64/Plugins/NetBox
@cp -f ./src/NetBox/*.lng ./Far3_x86/Plugins/NetBox
@cp -f ./*.md ./Far3_x64/Plugins/NetBox
@cp -f ./*.md ./Far3_x86/Plugins/NetBox
@cp -f ./ChangeLog ./Far3_x64/Plugins/NetBox
@cp -f ./ChangeLog ./Far3_x86/Plugins/NetBox
@cp -f ./LICENSE.txt ./Far3_x64/Plugins/NetBox
@cp -f ./LICENSE.txt ./Far3_x86/Plugins/NetBox
@cp -f ./Far3_x64/Plugins/NetBox/* ./build/x64/Far/Plugins/NetBox
@cp -f ./Far3_x86/Plugins/NetBox/* ./build/x86/Far/Plugins/NetBox
@cp -f ./Far3_x86/Plugins/NetBox/* ./build/NetBox/x86
@cp -f ./Far3_x64/Plugins/NetBox/* ./build/NetBox/x64
@cd /d src\NetBox\scripts
@gawk "/PLUGIN_VERSION_TXT/ {print $3}" ../resource.h > version.tmp
@for /F %%i in (version.tmp) do set PLUGINVER=%%i
@gawk "/NETBOX_VERSION_BUILD/ {print $3}" ../plugin_version.hpp > version.tmp
@for /F %%i in (version.tmp) do set PLUGREV=%%i
@rm -f version.tmp
@set PKGNAME=Far%PLUGINNAME%-%PLUGINVER%.%PLUGREV%_%FARVER%
@set RLSDIR=%BLDDIR%\vs%VSVER%\Release
@if not exist %PKGDIR% mkdir %PKGDIR% > NUL
@if exist %PKGDIR%\x64 rmdir /S /Q %PKGDIR%\x64 > NUL
@mkdir %PKGDIR%\x64 > NUL
@if not exist %BLDDIR%\x64\%BIN% mkdir %BLDDIR%\x64\%BIN% > nul
@copy /b /y %PLGDIR%\x64\* %PKGDIR%\x64 > NUL
@copy /b /y %RLSDIR%\x64\%PLUGINNAME%.map %PKGDIR%\x64 > NUL
@copy /b /y %PLGDIR%\x64\* %BLDDIR%\x64\%BIN%> NUL
@copy /b /y %RLSDIR%\x64\%PLUGINNAME%.map %BLDDIR%\x64\%BIN% > NUL
@call "C:\Program Files\7-Zip\7z.exe" a -mx9 -t7z -r %BLDDIR%\%PKGNAME%_x64.7z %PKGDIR%\x64\* > NUL
@if exist %PKGDIR%\x86 rmdir /S /Q %PKGDIR%\x86 > NUL
@mkdir %PKGDIR%\x86 > NUL
@if not exist %BLDDIR%\x86\%BIN% mkdir %BLDDIR%\x86\%BIN% > nul
@copy /b /y %PLGDIR%\x86\* %PKGDIR%\x86 > NUL
@copy /b /y %RLSDIR%\x86\%PLUGINNAME%.map %PKGDIR%\x86 > NUL
@copy /b /y %PLGDIR%\x86\* %BLDDIR%\x86\%BIN%> NUL
@copy /b /y %RLSDIR%\x86\%PLUGINNAME%.map %BLDDIR%\x86\%BIN% > NUL
@call "C:\Program Files\7-Zip\7z.exe" a -mx9 -t7z -r %BLDDIR%\%PKGNAME%_x86.7z %PKGDIR%\x86\* > NUL
@rmdir /S /Q %PKGDIR%
@cd /d ..\..\..\
@rm -fR ./build/NetBox/x64/*.map  ./build/NetBox/x86/*.map > nul
@rm -fR ./build/NetBox/Far3 > nul
@rm -fR ./build/VC10  ./build/VC14 > nul
@rm -fR ./Build/Release > nul
@rm -fR ./Far3_x64 > nul
@rm -fR ./Far3_x86 > nul
@rm -fR ./build/vs2010 ./build/vs2015> nul
@exit
```

**Comment by VictorVG** [comment]
Отыскал первопричину бага - рунтаймы CRT VC2015/2017 - файл utility_desktop.cpp в строке 128 которого сидит некорректный брекпойнт есть только по таким адресам:

.\Microsoft Visual Studio\2017\_редакция MSVS_\VC\Tools\MSVC\14.10.25017\crt\src\vcruntime\utility_desktop.cpp
.\Microsoft Visual Studio 14.0\VC\crt\src\vcruntime\utility_desktop.cpp

и более нигде его нет.

**Comment by grechnik** [comment]
Это не баг в рантайме VC. "Некорректный брекпойнт" - это программа извещает отладчик, что "я падаю, это последний шанс что-то сделать перед ExitProcess". В VC10 оно работает только потому, что VC10 не знает про C++11 (что логично).

Падает оно вот так:
` # Child-SP          RetAddr           Call Site`
`00 00000000002ead78 0000000076d128db ntdll!NtTerminateProcess+0xa`
`01 00000000002ead80 000007fee378eb84 ntdll!RtlExitUserProcess+0x9b`
`02 00000000002eadb0 000007fee378eb20 NetBox!exit_or_terminate_process+0x48 [d:\th\minkernel\crts\ucrt\src\appcrt\startup\exit.cpp @ 129]`
`03 00000000002eade0 000007fee3790b98 NetBox!common_exit+0x150 [d:\th\minkernel\crts\ucrt\src\appcrt\startup\exit.cpp @ 269]`
`04 00000000002eae10 000007fee378f99e NetBox!abort+0x54 [d:\th\minkernel\crts\ucrt\src\appcrt\startup\abort.cpp @ 89]`
`05 00000000002eae40 000007fee3779575 NetBox!terminate+0x26 [d:\th\minkernel\crts\ucrt\src\appcrt\misc\terminate.cpp @ 58]`
`06 00000000002eae70 000007fee377af10 NetBox!__std_terminate+0x9 [f:\dd\vctools\crt\vcruntime\src\eh\frame.cpp @ 2414]`
`07 00000000002eaea0 000007fee3779156 NetBox!_CallSettingFrame+0x20 [f:\dd\vctools\crt\vcruntime\src\eh\amd64\handlers.asm @ 50]`
`08 00000000002eaed0 000007fee3779f32 NetBox!__FrameUnwindToState+0x116 [f:\dd\vctools\crt\vcruntime\src\eh\frame.cpp @ 1119]`
`09 00000000002eaf40 000007fee3779302 NetBox!__FrameUnwindToEmptyState+0x7e [f:\dd\vctools\crt\vcruntime\src\eh\amd64\trnsctrl.cpp @ 149]`
`0a 00000000002eaf80 000007fee377a2e5 NetBox!__InternalCxxFrameHandler+0x12e [f:\dd\vctools\crt\vcruntime\src\eh\frame.cpp @ 396]`
`0b 00000000002eaff0 0000000076d181ad NetBox!__CxxFrameHandler3+0x6d [f:\dd\vctools\crt\vcruntime\src\eh\amd64\trnsctrl.cpp @ 186]`
`0c 00000000002eb040 0000000076d07ddc ntdll!RtlpExecuteHandlerForUnwind+0xd`
`0d 00000000002eb070 0000000076c0052e ntdll!RtlUnwindEx+0x539`
`0e 00000000002eb710 000007fee377a25d kernel32!RtlUnwindExStub+0x1e`
`0f 00000000002eb750 000007fee377826c NetBox!_UnwindNestedFrames+0x109 [f:\dd\vctools\crt\vcruntime\src\eh\amd64\trnsctrl.cpp @ 481]`
`10 00000000002ebd10 000007fee377864d NetBox!CatchIt+0xa8 [f:\dd\vctools\crt\vcruntime\src\eh\frame.cpp @ 1268]`
`11 00000000002ebd90 000007fee37793fd NetBox!FindHandler+0x33d [f:\dd\vctools\crt\vcruntime\src\eh\frame.cpp @ 679]`
`12 00000000002ebe70 000007fee377a2e5 NetBox!__InternalCxxFrameHandler+0x229 [f:\dd\vctools\crt\vcruntime\src\eh\frame.cpp @ 449]`
`13 00000000002ebee0 0000000076d1812d NetBox!__CxxFrameHandler3+0x6d [f:\dd\vctools\crt\vcruntime\src\eh\amd64\trnsctrl.cpp @ 186]`
`14 00000000002ebf30 0000000076d0855f ntdll!RtlpExecuteHandlerForException+0xd`
`15 00000000002ebf60 000000076d3bcb8 ntdll!RtlDispatchException+0x45a`
`16 00000000002ec640 000007fefca2a06d ntdll!KiUserExceptionDispatch+0x2e`
`17 00000000002ecd70 000007fee3779c32 KERNELBASE!RaiseException+0x39`
`18 00000000002ece40 000007fee37d0957 NetBox!_CxxThrowException+0xc2 [f:\dd\vctools\crt\vcruntime\src\eh\throw.cpp @ 136]`
`19 00000000002ecec0 000007fee382d132 NetBox!THierarchicalStorage::CloseSubKey+0x67 [g:\dev\test\far-netbox\src\core\hierarchicalstorage.cpp @ 206]`
`1a 00000000002ecf20 000007fee3828341 NetBox!TFar3Storage::CloseSubKey+0xe [g:\dev\test\far-netbox\src\netbox\far3storage.cpp @ 90]`
`1b (Inline Function) ---------------- NetBox!TGUIConfiguration::LoadData::__l22::<lambda_91b56117663c95e771bbf70dbf449fc7>::operator()+0x10 [g:\dev\test\far-netbox\src\windows\guiconfiguration.cpp @ 822]`
`1c (Inline Function) ---------------- NetBox!detail::scope_guard<<lambda_91b56117663c95e771bbf70dbf449fc7> >::{dtor}+0x10 [g:\dev\test\far-netbox\src\base\sysutils.hpp @ 485]`
`1d 00000000002ecf50 000007fee382d88d NetBox!TGUIConfiguration::LoadData+0x10ad [g:\dev\test\far-netbox\src\windows\guiconfiguration.cpp @ 825]`
`1e 00000000002ed0f0 000007fee37b69e7 NetBox!TFarConfiguration::LoadData+0x2d [g:\dev\test\far-netbox\src\netbox\farconfiguration.cpp @ 149]`
`1f 00000000002ed1a0 000007fee37b68fb NetBox!TConfiguration::LoadFrom+0x57 [g:\dev\test\far-netbox\src\core\configuration.cpp @ 443]`
`20 00000000002ed1e0 000007fee37bea7c NetBox!TConfiguration::Load+0x73 [g:\dev\test\far-netbox\src\core\configuration.cpp @ 458]`
`21 00000000002ed2c0 000007fee3892a4f NetBox!CoreLoad+0x80 [g:\dev\test\far-netbox\src\core\coremain.cpp @ 136]`
`22 00000000002ed330 000007fee389384e NetBox!TWinSCPPlugin::CoreInitializeOnce+0x17 [g:\dev\test\far-netbox\src\netbox\winscpplugin.cpp @ 858]`
`23 00000000002ed360 000007fee383b7a5 NetBox!TWinSCPPlugin::GetPluginInfoEx+0x2e [g:\dev\test\far-netbox\src\netbox\winscpplugin.cpp @ 63]`
`24 00000000002ed3a0 000007fee383cbc7 NetBox!TCustomFarPlugin::GetPluginInfo+0xa9 [g:\dev\test\far-netbox\src\netbox\farplugin.cpp @ 166]`
`25 00000000002ed660 000000013fc1c571 NetBox!GetPluginInfoW+0x37 [g:\dev\test\far-netbox\src\netbox\netbox.cpp @ 63]`

Падает оно по двум причинам.

Причина номер раз: `TGUIConfiguration::LoadData` вызывает несколько раз `Storage->OpenSubKey(...)`, но *не проверяет* возвращаемое значение. А оно, между прочим, false. По коду может показаться, что проверка есть, но `try__finally` - это макрос, раскрываемый в `(void)0;`, так что код в следующих фигурных скобках исполняется всегда.

Причина номер два: выброс исключения в деструкторе. `Storage->CloseSubKey()` при попытке закрыть что-то, чего оно не смогло открыть, бросает исключение. SCOPE_EXIT - это макрос, который в конечном счёте выполняет переданный ему код в деструкторе `detail::scope_guard`. Согласно стандарту C++11, деструкторы без явной спецификации `noexcept(...)` получают неявную спецификацию `noexcept(true)`, если какой-то из членов класса или базовый класс имеет деструктор с `noexcept(true)`, и `noexcept(false)` в противном случае. Для `scope_guard::~scope_guard` неявная спецификация получается как раз `noexcept(true)`, и исключение внутри него не выходит наружу, а вызывает `terminate()`. (Кстати, я не отслеживал, а таки есть где-то выше по стеку перехватчик исключений? Если в VC10 работает, то, наверное, есть...) Лечится дописыванием явного `noexcept(false)` после `scope_guard::~scope_guard()`.

**Comment by VictorVG** [comment]
Понятно. В PL/1 OS/360 был схожий механизм, только там такая ошибка заканчивалась вызовом обработчика исключений из либ компилятора, а тот выводил сообщение вида _"IEF1789 Unknown runtime error. Job's is terminated."_  о сбое на консоль оператора, в итоге чего девчонки звали шефа системщиков, дядя Толя брал том системных сообщений, задумчиво смотрел через "_глаз системного программиста_" (управляющий пакет "ОКО" :)) таблицы главного планировщика кому на сей раз "спасибы" говорить и в  курилке слышался его рык и жалобно-оправдывающееся блеяние виновного на весь ВЦ.:)

**Comment by VictorVG** [comment]
**FIXED**

Проверено на VC2010 SP1 и VC2015 Update 3 в NetBox v2,4,3,485 Git-79c2ef2c93f9:

1) Скрипты собирают в VC2010 и в VC2015 - эта проблема пофикшена;
2) Падения собранного в VC2015 варианта более не наблюдаю в не зависимости от того в какой версии компилятора собрана NetBox.dll, наличия БД созданной в предыдущих  версиях NetBox и запущенного плагина D&D - данная проблема так же пофикшена;

В связи с устранением обозначенных в данном инце проблем думаю что его можно закрыть и добавить в changelog в запись _* Bugfix: plugin crashes on FAR startup_ строку:

  _(https://github.com/michaellukashov/Far-NetBox/issues/230)_

P.S.

Пока не закрыл - вдруг у кого ещё есть  какие замечания по данному инцу?

**Comment by VictorVG** [comment]
Пометил как FIXED: чтобы не путал. Паники нам ещё не хватает.:)

**Comment by VictorVG** [comment]
Замечаний вроде нет, закрываем.
