### ISSUE TITLE
Command "cd" not working in command line

### ISSUE THREAD

**Issue by blabulabul** [michaellukashov/Far-NetBox#240]
Few builds ago stopped working "cd" in command line. In the FarNetBox 2.4.3.492 it worked, but in actual 2.4.3.505 it shows message dialog "Current SFTP-3 session does not support command you request. Separate shell session may be opened to process..." and it is not possible to change the directory via command line.

**Comment by VictorVG** [comment]
Duplicate - [**v2.4.3.505: из-за сломанной команды cd некорректно обрабатываются аллиасы каталогов #239**](https://github.com/michaellukashov/Far-NetBox/issues/239)

**Comment by VictorVG** [comment]
Fixed use https://github.com/michaellukashov/Far-NetBox/issues/241#issuecomment-311965925

**Comment by VictorVG** [comment]
[**FarNetBox-2.4.3.505_Far3_x64_fix.7z**l(https://yadi.sk/d/1scnDCOH3KbkfE)
[**FarNetBox-2.4.3.505_Far3_x86_fix.7z**](https://yadi.sk/d/iFc3gRSp3Kbkh6)

**Comment by VictorVG** [comment]
Fixed
