### ISSUE TITLE
FIXED: Host name is displayed instead of a session's name

### ISSUE THREAD

**Issue by ms2048** [michaellukashov/Far-NetBox#243]
If the option '[] Show session name in window title' is set then the host name (usually an IP address in my case) is instead prepended to the title in the newest NetBox 2.4.3 build 505 with Far 3.0.4980 x86, which is confusing / unfortunate.

This is a regression, I've just updated from NetBox 2.4.0 build 438 with Far 3.0.4863 x86, where the session name has always been correctly displayed.

**Comment by VictorVG** [comment]
See [**gh #229: show only host name and current dir**](https://github.com/michaellukashov/Far-NetBox/commit/adfcad42755b81695be18686368d9c6a6e6466b9) and [**Убрать префикс netbox: в заголовке #229**](https://github.com/michaellukashov/Far-NetBox/issues/229) for details.

**Comment by ms2048** [comment]
OK, so the name of the option is wrong in English ("Show session name ...").

Is there any chance of giving the previous behavior back?

As an additional configuration option perhaps? Pretty please! :)

The rationale would be that the session name can be tailored to be:
- more readable
- more informative
- shorter and to the point

than the hostname.

For example, sometimes I have three different kinds of connections (different users, etc.) to the same host and now there is no way to distinguish between them. Also, I don't know ip addresses of my hosts by heart.

**Comment by ms2048** [comment]
Also, to clarify: the prefix "netbox:" in title is clearly only wasting space, so I fully support the removal of it. On the other hand, the name of the session itself was very useful for me.

**Comment by VictorVG** [comment]
Now I finish with one work (it's not clear that the git in the logs displays - with git's one list of changes, and from the same repository, but through SVN is completely different), and then in the head of confusion - the partner needs to diff for the transfer, and where the truth ? and look.

**Comment by ms2048** [comment]
I'm sorry, I don't quite understand... what 'truth' do you mean? Are you referring to some unfortunate merge of diffs? SVN can be a bit of a pain in this regard...

Anyway, is there any chance of re-adding current session's name to the title of the window / tab, just like it was in (for example) 2.4.0.438? I'd like that.

If the above is not your preferred way of solving this, maybe just add another configuration option, something like this:

Prepend window and tab title with:
( ) session's name ( ) hostname ( ) nothing

**Comment by VictorVG** [comment]
I tested. **Fixed**.

**Comment by ms2048** [comment]
Works for me. Thanks!

**Comment by VictorVG** [comment]
You are welcome. You had an old version, but there was still a mistake that was fixed later.

**Comment by VictorVG** [comment]
**FIXED**

**Comment by VictorVG** [comment]
Thanks!
