### ISSUE TITLE
Падение при последовательном изменении файла по Alt-F4

### ISSUE THREAD

**Issue by 9-11** [michaellukashov/Far-NetBox#245]
Чтобы воспроизвести падение:
1. Заходим на сервер по FTP или SCP
2. Открываем тестовый файл на сервере во внешнем редакторе (Alt-F4), изменяем, сохраняем
3. Снова открываем тот же файл во внешнем редакторе по Alt-F4. В этот момент происходит падение
Если между пунктом 2 и 3 принудительно обновить панель (Ctrl-R), то падения на втором открытии не происходит.

Причина в следующем. Far хранит список элементов панели плагина. Каждый элемент имеет поле PluginPanelItem.UserData.Data, в котором NetBox хранит соответствующий этому элементу объект TRemoteFile. После сохранения файла в пункте 2, NetBox перечитывает директорию, удаляя старые объекты TRemoteFile и создавая новые. Но Far не обновляет список элементов панели, поэтому при новом открытии файла (пункт 3) NetBox пытается использовать старый указатель из PluginPanelItem.UserData.Data, который уже освобождён.

Возможный фикс состоит в том, чтобы вставить в самый конец функции `intptr_t TWinSCPFileSystem::UploadFiles(bool Move, OPERATION_MODES OpMode, bool Edit,
  UnicodeString & DestPath)` вызов `UpdatePanel()`:

`intptr_t TWinSCPFileSystem::UploadFiles(bool Move, OPERATION_MODES OpMode, bool Edit,
  UnicodeString & DestPath)`
`{`
  `...`
  +`UpdatePanel();`
  `return Result;`
`}`

**Comment by VictorVG** [comment]
Diff сделал:
```
--- ./src/NetBox/WinSCPFileSystem.cpp	Git-bbf271c03814c04cffe5f73454bdc8300a887e11
+++ ./src/NetBox/WinSCPFileSystem.cpp	Wed Jul 05 16:10:08 2017
@@ -2743,6 +2743,7 @@
   {
     Result = -1;
   }
+  UpdatePanel()
   return Result;
 }
 
@@ -4235,4 +4236,3 @@
     reinterpret_cast<uint8_t *>(const_cast<char *>(Result.c_str())));
   return BytesToHex(Result);
 }
-

```
скомпилится и посмотрим как он себя поведёт.

**Comment by VictorVG** [comment]
Diff:

```
--- ./src/NetBox/WinSCPFileSystem.cpp	Git-bbf271c03814c04cffe5f73454bdc8300a887e11
+++ ./src/NetBox/WinSCPFileSystem.cpp	Wed Jul 05 16:10:08 2017
@@ -2743,6 +2743,7 @@
   {
     Result = -1;
   }
+  UpdatePanel()
   return Result;
 }
 
@@ -4235,4 +4236,3 @@
     reinterpret_cast<uint8_t *>(const_cast<char *>(Result.c_str())));
   return BytesToHex(Result);
 }
-

```

Соберу, перепроверю. Не собрался по моей вине (и я зря коммент удалил :( ).

**Comment by VictorVG** [comment]
О! Порядок в танковых войсках! Не падает. Проверял на Notepad через ассоцииаци 

![1](https://user-images.githubusercontent.com/906886/27867412-3ab0668a-61a2-11e7-8d01-1ebf5977f83f.png)

[**NetBox_2.4.3.509_x86_AMD64_fix.zip**](https://github.com/michaellukashov/Far-NetBox/files/1124843/NetBox_2.4.3.509_x86_AMD64_fix.zip)

Можно фикс коммитить.

**Comment by VictorVG** [comment]
Версию 2.4.3.510 x86 и x64 собрал и выложил в [**./Far3**](https://yadi.sk/d/oc1fPSIbhvvwT)

**Comment by VictorVG** [comment]
**FIXED**
