### ISSUE TITLE
SCP не отображает листинг

### ISSUE THREAD

**Issue by 2underscores-vic** [michaellukashov/Far-NetBox#246]
NetBox v 2.4.3 build 492

В логе ошибка:

```
* 2017-07-28 13:32:49.956 
* 2017-07-28 13:32:49.956 Unexpected directory listing line «drwxr-xr-x  6 root             root         4096 2017-07-27 10:44:52.404136754 +0300 .».
```

Если сессию поменять на SFTP, то всё показывается.

**Comment by VictorVG** [comment]
А обновится не пробовали? Текущая версия 2.4.4.516 давно доступна.

**Comment by 2underscores-vic** [comment]
Обновляю Far только целиком и только на стабильные сборки. Но если проблема там решена... Попробую. Можно ссылку, откуда качать?

**Comment by 2underscores-vic** [comment]
В релизах нашёл 512 - лучше не стало.

Почему "Unexpected directory listing" есть понимание?

**Comment by VictorVG** [comment]
Ну, например в любой ночнушке есть текущий NB, у меня на сервере он просто отдельно лежит в [**./Far3**](https://yadi.sk/d/oc1fPSIbhvvwT). Можете смело распаковать архив поверх текущей копии плагина - сегодня он собирается для b4400, так что и в более новых будет работать. Версия для х86 собрана для XP SP3 и выше, x64 для Vista и выше - это особенности линковки в VC++2010.

**Comment by 2underscores-vic** [comment]
Не, ничего не меняется.

**Comment by VictorVG** [comment]
Не зная что за сервер на котором вы проверяете ответить о причине наблюдений нельзя. Может там SCP или SFTP а вы пытаетесь подключится по FTP и сервер рвёт соединение?

**Comment by 2underscores-vic** [comment]
Какой "рвёт соединение"? Почему в логах про это ничего нет? Фрагмент лога, который я привёл видели?

**Comment by VictorVG** [comment]
Он "пустой", а я не телепат гадать по паре строк о том, что вы решили скрыть.

**Comment by 2underscores-vic** [comment]
Unexpected directory listing line «drwxr-xr-x  6 root             root         4096 2017-07-27 10:44:52.404136754 +0300 .».

**Comment by 2underscores-vic** [comment]
Что значит это сообщение?

**Comment by VictorVG** [comment]
Без основной части лога всё, что угодно. Включите логирование уровня Отладка 2 в настройках NB и по тому логу можно будет разбираться. По этой строке ответ дать нельзя.

**Comment by VictorVG** [comment]
Собрал в vc++2010, выложил в [**./Far3**](https://yadi.sk/d/oc1fPSIbhvvwT). Посмотрел в работе на [**ftp://ftp5.gwdg.de/pub/FreeBSD/releases/ISO-IMAGES/11.1/FreeBSD-11.1-RELEASE-i386-bootonly.iso.xz**](ftp://anonymous:@ftp5.gwdg.de:21/pub/FreeBSD/releases/ISO-IMAGES/11.1/FreeBSD-11.1-RELEASE-i386-bootonly.iso.xz) так как там используется сложный каскад межсерверных переходов хорошо ловящий сбои (но таймаут обновления панелей тут может достигать пары - тройки минут) - по SHA-256 файл скачан без ошибок. Сам сервер ftp://ftp5.gwdg.de/pub/ содержит зеркала и архивы многих проектов, например в ./TDF лежит основной FTP проекта Libre Office что позволяет взять что надо минуя просмотр рекламы (я лично её на дух не переношу). ;)

**Comment by 2underscores-vic** [comment]
[scp-log.txt](https://github.com/michaellukashov/Far-NetBox/files/1186680/scp-log.txt)

В панели видны только следующие файлы:


```
.git
.gitignore
AUTHORS
ChangeLog
COPYING
INSTALL
Makefile.am
Makefile.in
```

**Comment by 2underscores-vic** [comment]
[scp-log2.txt](https://github.com/michaellukashov/Far-NetBox/files/1186746/scp-log2.txt)

Вот лог поинтереснее, если нажать Ctrl+R. В этот раз на `FarNetBox-2.4.4_Far3_x64.7z`

**Comment by VictorVG** [comment]
Ну, для Git это ожидаемо так как Git это распределённая P2P система где данные находятся на множестве независимых хостов, но отображаются на виртуальный корневой каталог репозитория.

**Comment by 2underscores-vic** [comment]
Причём тут git вообще?! Есть каталог на диске, содержимое которого **плагин показывает неправильно**, спотыкаясь на файле `NEWS`

**Comment by VictorVG** [comment]
Я вижу у вас в корне каталога характерную для Git структуру:

./.git
./.gitignore

что заставляет задуматься.

**Comment by michaellukashov** [comment]
Проблема в нестандартном имени пользователя.
Проверьте сегодняшнюю ночную сборку FAR3 - должно быть исправлено.

**Comment by 2underscores-vic** [comment]
Да, в v 2.4.4 build 519 проблема исчезла.
Спасибо большое!

**Comment by 2underscores-vic** [comment]
Там и группа `Domain Users`, кстати, неправильно парсится в одном месте, судя оп логу:
```
. 2017-08-01 13:34:39.505 Following membership found:
. 2017-08-01 13:34:39.505   "Domain" [0]
. 2017-08-01 13:34:39.505   "Users" [0]
. 2017-08-01 13:34:39.505   "vpn_users" [0]
...
```
Только не знаю, влияет ли это на что-то.

**Comment by VictorVG** [comment]
Посмотрите версию 2.4.4.522. Давно доступна.

**Comment by VictorVG** [comment]
Версия 2.4.4.524 есть у меня в ./Far3. Проверьте как она у вас работает? Там исправлена ошибка с реконнектом.

**Comment by 2underscores-vic** [comment]
У меня не было никаких проблем с реконнектом

**Comment by 2underscores-vic** [comment]
Вышел релизный Far3 build 5000. Закрываю

**Comment by VictorVG** [comment]
@2underscores-vic 

Маркировка состояния разработки проекта Far (Stable / Nightly) никак не завязана на плагины. Для них  важен только минимальный номер билда Far, а для нас принципиально важно только одно - ошибка исправлена или нет.
