### ISSUE TITLE
Некорректный выход из сессии запущенной по CtrlPgDn если в ней производилось копирование.

### ISSUE THREAD

**Issue by VictorVG** [michaellukashov/Far-NetBox#247]
**Что происходит?** 

При переходе по AltF[1,2][A-Z, a-z] на другой диск в случае запуска сессии по CtrlPgDn последний скопированный на сервер файл/каталог ошибочно обрабатывается плагином как данные резервной копии конфигурации сессии с выводом окна запроса импорта сессии из данного файла/каталога.

**Необходимый инструментарий:**

Минимальный набор бинарников (неиспользуемые .hlf/.lng можно сразу выкинуть) Far:

_./Far.exe
Far.exe.ini
FarEng.hlf
FarEng.lng
FarRus.hlf
FarRus.lng
plugins
./plugins/netbox:
NetBox.dll
NetBoxEng.lng
NetBoxRus.lng_

В Far.exe.ini ставим значения:

```
[General]
UseSystemProfiles=0
UserProfileDir=%FARHOME%\Profile
GlobalUserMenuDir=%FARHOME%
TemplateProfile=%FARHOME%\Default.farconfig
DefaultLanguage=Russian
UserLocalProfileDir=%FARHOME%\Profile
```
FTP/HTTP/WebDAV аккаунт с правом записи на сервер.

NetBox с настроенной на данный аккаунт сессией.

**Методика проверки:**

1) эапускаем Far, на любой панели запускаем NetBox, на противоположной панели открыт любой каталог, 
2) переключаемся на панель сессий NetBox,  
3) запускаем тест-сессию по CtrlPgDn, 
4) после логона на сервер по TAB переключаемся TAB на пассивную (файловую) панель, 
5) по F5 копируем какой-нить файл или каталог 
6) после завершения копирования на панели NetBox выполняем `AltF[1,2][A-Z, a-z]` (AltF1/AltF2 + буква любого диска)

Результат - окно запроса импорта сессии.

**P.S.**

_Ошибка воспроизводится на Far b4995 x64 + NetBox v2.4.4.518 и на более ранних версиях._

**Comment by VictorVG** [comment]
Собрал Far b4996 x64 и NetBox v2.4.4.519, проверил по описанной в инце методике - пока явление присутствует.

**Comment by z0hm** [comment]
Проявляется не только при выходе из сессии по AltF[1,2], но и при выходе вообще - по CtrlPgUp, по Enter. Поэтому инц лучше озаглавить так: Некорректный выход из сессии при входе по CtrlPgDn, если внутри сессии использовалось копирование.

**Comment by VictorVG** [comment]
Поправил.

**Comment by VictorVG** [comment]
Добро. Сейчас и соберём. Только что увидел. Спасибо!

P.S.

Для смеха - **WildGoblin**

>> а лучше сменить само устройство, например на 3COM, Microtek или в крайнем случае ZyXEL
> Plink хорошие устройства делает - не хуже чем асус!
>  
> 3COM давным давно нет в живых. Микротик - обычному домашнему пользователю его возможности никогда не понадобятся. А ZyXEL - когда-то да, но сейчас я бы его не взял.

Он этой фотки платы TP-Link TL-R460 не видел:

![tp-link_tl-r460](https://user-images.githubusercontent.com/906886/28945860-e70bea6a-78b0-11e7-983f-914072f9ec11.jpg)

память 8 Мб SDRAM на 143 МГц, работает на частоте 167 МГц, Ос при запуске забивает память на 7,8 - 7,9 Мб из 8, и вдобавок прошивка тришкин кафтан с кучей  не понятно для чего оставленных модулей которые грузятся в ОЗУ. А оставшиеся 100 - 200 Кб используют антивирус,  таблицы маршрутов, DNS, DHCP, FTP, NAT, DMZ и VPN вдогонку.:) Явно экономили на всём, на чём смогли и девайс на трафике выше 15 Мб/с  виснет наглухо.:)
