### ISSUE TITLE
Перестали выполняться удалённые команды в сеансе SFTP/SCP

### ISSUE THREAD

**Issue by HamRusTal** [michaellukashov/Far-NetBox#258]
**Воспроизвести:**
1. Открываю панель SFTP/SCP — хоть на Линукс, хоть на макОСь; авторизация хоть ключом, хоть паролем.
2. Из командной строки выполняю команду — например, “`umask 0002`”.

**Ожидаю:** команда отрабатывает, выводится код возврата (`0`).

**Получаю:** по нажатию на `Enter` в конце команды просто _ничего не происходит_. Т.е., похоже, SSH от SCP просто отломали.

**Регрессия:**
В версии _NetBox 2.4.5.526 12.08.2017_ (из _`Far30b5006.x86.20170815.7z`_) ошибка уже есть; в версии _NetBox 2.4.4.524 09.08.2017_ (из _`Far30b5004.x86.20170812.7z`_) ещё нет.

**См. тж.:** [На багтрекере Фара](http://bugs.farmanager.com/view.php?id=3474). [На форуме](https://forum.farmanager.com/viewtopic.php?f=5&t=6317&p=145483#p145483).

**Comment by VictorVG** [comment]
Начиная с WinSCP 5.10.3 beta её авторы щедро дров наломали:

_Потеря данных в NetBox v2.4.5.526/v2.4.5.527 при фоновой передаче с FTP - потеря имён и типа файлов приводящая к их перезаписи
#256 opened on 10 Sep by VictorVG

NetBox v2.4.5.526/.527 - игнорирование RFC-1738 при разборе анонимных URL начиная с WinSCP v5.10.3 beta
#255 opened on 7 Sep by VictorVG

NetBox v2.4.5.526/2.4.5.527 - ошибки ssh/scp
#253 opened on 26 Aug by VictorVG

NetBox v2.4.5.527: FTP URL:22 в БД не пишется поле PortNumber и при перезапуске сессии порт сбрасывается на умолчания протокола.
#252 opened on 22 Aug by VictorVG_

и поэтому для себя я давно откатился на 2.4.4.524 - там ошибки конечно есть, но хоть данные она не теряет.:)

**Comment by HamRusTal** [comment]
Исправлено, проверял в Far Manager v3.0 build 5273 x86 (2018-09-28).
Изменить статус заявки почему-то не получается.

**Comment by VictorVG** [comment]
Нажмите Close под формой отправки комментария. Остальное система сама сделает.
