### ISSUE TITLE
Possible security issue with WinSCP < 5.14

### ISSUE THREAD

**Issue by onyxmaster** [michaellukashov/Far-NetBox#279]
https://www.zdnet.com/article/scp-implementations-impacted-by-36-years-old-security-flaws/

**Comment by 0xABD** [comment]
Fixed in original WinSCP source here: https://winscp.net/tracker/1675
Commit of fix in WinSCP: https://github.com/winscp/winscp/commit/49d876f2c5fc00bcedaa986a7cf6dedd6bf16f54
Seems straightforward to backport

**Comment by VictorVG** [comment]
**0xABD** 

Can't build than try apply Your patch to Git dbb8ff2 possible is my typo, but if use VC2010/2015 DLL not build .:(

**Comment by skipik** [comment]
I built it including those fixes without any problem. I used VS2017 though.
https://www.upload.ee/files/9454385/FarNetBox-2.4.5.531_Far3_x86.7z.html
https://www.upload.ee/files/9454390/FarNetBox-2.4.5.531_Far3_x64.7z.html

**Comment by VictorVG** [comment]
Ok. Only this compiller not't tested - no time...

**Comment by VictorVG** [comment]
Build Ok!, problem's source is my typo. Fixed, but not tested. Build in to VC2010.

P.S.

Как обычно - одновременно делать работу, и писать _бумаги_  - какой злой дух придумал сиё наказание!?:( Да мне легче дивизию чертей наловить, обстричь, рога поотшибать и вместе с шерстью сдать в счёт госпаставок - в Аду тепло, не замёрзнут.:)

**Comment by VictorVG** [comment]
Tested - Ok! Additional test - download  FreeBSD 12 STABLE images - it's not so easy to get to them. on the servers of the _daemon_, a cascade of inter-server symlinks is used - the images lie on a cluster of NFS servers and this is a good test for "_have we not broken the work with symlinks and FTP_?" and work with complex server systems.

The same cascade, for example, does not allow to see the real size of the file ftp://ftp.freebsd.org/pub/FreeBSD/ports/ports/ports.tar.gz - through the symlink it is addressed ftp://ftp.freebsd.org/pub/ FreeBSD/development/tarballs/ports_current.tar.gz and if you don’t know this, you won’t find the file.

**Comment by VictorVG** [comment]
Whats new?:) If try VC++2010 build and open for update 7-Zip archive in to local FTP have  crash in to GetFilesW():

![1](https://user-images.githubusercontent.com/906886/51598546-d67c8a00-1f0e-11e9-8a03-8f63600e5668.png)

and stack:

```
Исключительная ситуация

0x7FEFD79A06D KERNELBASE.dll!RaiseException
0x00140271B32 Far.exe!<unknown> (get the pdb)
0x001402731AD Far.exe!<unknown> (get the pdb)
0x001400981A0 Far.exe!<unknown> (get the pdb)
0x001402BCEF0 Far.exe!<unknown> (get the pdb)
0x00140273460 Far.exe!<unknown> (get the pdb)
0x00140270A6C Far.exe!<unknown> (get the pdb)
0x00077A8B681 ntdll.dll!RtlRestoreContext
0x00140174716 Far.exe!<unknown> (get the pdb)
0x001401735A9 Far.exe!<unknown> (get the pdb)
0x00140170D55 Far.exe!<unknown> (get the pdb)
0x001401983BB Far.exe!<unknown> (get the pdb)
0x001400C1E5B Far.exe!<unknown> (get the pdb)
0x001400C412A Far.exe!<unknown> (get the pdb)
0x001400E5E60 Far.exe!<unknown> (get the pdb)
0x00140145385 Far.exe!<unknown> (get the pdb)
0x00140144689 Far.exe!<unknown> (get the pdb)
0x001401444E9 Far.exe!<unknown> (get the pdb)
0x0014013DFC1 Far.exe!<unknown> (get the pdb)
0x00140140ECD Far.exe!<unknown> (get the pdb)
0x00140141082 Far.exe!<unknown> (get the pdb)
0x00140141194 Far.exe!<unknown> (get the pdb)
0x001401411C2 Far.exe!<unknown> (get the pdb)
0x0014014114E Far.exe!<unknown> (get the pdb)
0x0014026F3E9 Far.exe!<unknown> (get the pdb)
0x000778359CD kernel32.dll!BaseThreadInitThunk
0x00077A6A561 ntdll.dll!RtlUserThreadStart

OK
```
(this build not have .PDB removed my toolkit then assembly). I try VC++2015 build and **skipik** VC++2017 build - possible also my typo? "Minidump" have "small" file size -- only 476 mb (this computer have is 16 Gb physical RAM).

**Comment by VictorVG** [comment]
Interesting - in one of the test copies replaced Far.exe taking it from the nightie. I started it - there is no failure with it, I returned my version - again there is no failure. Clearly something local is wrong ...

**Comment by VictorVG** [comment]
Я дико извиняюсь, но не могу сообразить с какого перепугу после внесённых в #280 изменений простой FTP стал SCP FTP? У меня вылазит запрос SCP пароля там где ему делать нечего, а после всё гвардейски падает...

**Comment by VictorVG** [comment]
VC++2010 [**NetBox v2.4.5.531 Git-a7345ca4f**](https://github.com/VictorVG/PLG/releases/tag/NB-a7345ca4f) minimal OS required: x86 - WinXP SP3, AMD64 - Vista .  

_Fix a typo in a failed commit_

**Comment by 0xABD** [comment]
@michaellukashov How can I help further with this issue? Also, how do we include the fix to Far mainline?

**Comment by 0xABD** [comment]
Reported into Far bug tracker at https://bugs.farmanager.com/view.php?id=3705

**Comment by trexinc** [comment]
merged
