### ISSUE TITLE
SFTP - ошибка при редактировании файла другого пользователя. 

### ISSUE THREAD

**Issue by AutopilotNN** [michaellukashov/Far-NetBox#324]
FAR 3.0.5888.0 x64

Конфигурация сервера (sshd с internal-sftp) составлена так, что пользователи пишут в один каталог и могут редактировать файлы друг друга - это позволяется через rwxrws--- и принадлежности к общей группе. Filezilla работает без ошибок. 

При редактировании чужого файла изменения сохраняются, но выводится сообщение ниже.  При этом в настройках плагина выставлено "Игнорировать ошибки прав" и убрано "Сохранять время изменения", а в настройках соединения убрано "Не менять время для файлов сервера"
Текст "Ошибка 2" появляется есть создать каталог. Собственно, использовать NetNox в SFTP невозможно. 

Ошибка 1
**Upload of file «index.html» was successful, but error
occurred while setting the permissions and/or timestamp.**

If the problem persists, turn off setting permissions or
preserving timestamp. Alternatively you can turn on
«Ignore permission errors» option.
────────────────────────────────────────────────────────────
Permission denied.
Error code: 3
Error message from server:

Ошибка 2
Cannot change properties of file «3».
──────────────────────────────────────
Permission denied.
Error code: 3
Error message from server:

**Comment by VictorVG** [comment]
Ждите, вероятно ошибка связана со старой WinSCP а это сейчас в работе.

**Comment by AutopilotNN** [comment]
Дело в том, что WinSCP не выдаёт ошибок, если убрать настройку "preserving timestamp" или поставить "Ignore permission errors" и отредактировать чужой файл, но NetBox, похоже, игнорирует эти настройки плагина. в WinSCP есть пресеты, возможно их библиотека в NetBox ищет настройки по-другому, т.к. в WinSCP используются пресеты.

**Comment by VictorVG** [comment]
@AutopilotNN 

А почему все, включая NetBox обязаны копировать поведение WinSCP? Особенно учитывая вольности её разработчиков в отношении соблюдения спецификаций IETF/RTF и ISO/IEC? Например при работе с URL WinSCP часто демонстративно игнорирует спецификации RTF и её разработчики об этом знают, но говорят "_Нам так удобно и что либо изменять мы не намерены!"_
