### ISSUE TITLE
Protocol version not supported (sftpng.cmegroup.com)

### ISSUE THREAD

**Issue by ujos** [michaellukashov/Far-NetBox#327]
Не могу подключиться сюда:

HostName: sftpng.cmegroup.com
Username: cmeconfig
Password: по ссылке [https://www.cmegroup.com/confluence/dis ... nformation](https://www.cmegroup.com/confluence/display/EPICSANDBOX/MDP+3.0+-+FTP+and+SFTP+Site+Information)

Во время подключения выводит на экран следующее и сразу закрывается

![image](https://user-images.githubusercontent.com/70940/219950435-4b63eb6d-2a05-44cc-b46a-ad2d30503362.png)

Через sftp подключение устанавливается без проблем:
```txt
$ sftp cmeconfig@sftpng.cmegroup.com
cmeconfig@sftpng.cmegroup.com's password:
Connected to sftpng.cmegroup.com.
sftp> ls -l
drwxrwsr-x    5 cmeconfig mainftp      4096 Jul 17  2015 DCMSGW
drwxrwsr-x    5 cmeconfig mainftp      4096 Jul 17  2015 MSGW
drwxrwsr-x    7 fixadmin mainftp      4096 Feb  9  2015 SBEFix
drwxrwsr-x    7 fixadmin mainftp      4096 Apr 11  2015 fix
sftp>
```

Attached is log file:
[sftpng.cmegroup.com.log.zip](https://github.com/michaellukashov/Far-NetBox/files/10776954/sftpng.cmegroup.com.log.zip)

Внизу файла находятся такие строки:

```txt
. 2023-02-19 14:14:44.186 Received disconnect message (protocol version not supported)
. 2023-02-19 14:14:44.186 Disconnection message text: Unable to use requested SFTP protocol version
. 2023-02-19 14:14:44.186 Server sent disconnect message
. 2023-02-19 14:14:44.186 type 8 (protocol version not supported):
. 2023-02-19 14:14:44.186 "Unable to use requested SFTP protocol version"
```

**Comment by VictorVG** [comment]
@ujos 

Судя по описанию `CME provides an FTP (https://www.cmegroup.com/ftp) and SFTP ([sftpng.cmegroup.com](http://sftpng.cmegroup.com/))` в основе лежит URL схема с протоколами HTTP/HTTPS и (по логу) там стоит SFTP сервер с AES256 шифрованием - `SSH-2.0-mod_sftp` что не позволяет подключится по "FTP" https://www.cmegroup.com/ftp и FileZilla Client 3.63.1:

![20230220_092849](https://user-images.githubusercontent.com/906886/220030275-e2cc4a98-9a23-42d7-8896-7cf91f2a6aa7.jpg)

т.к. мы указали клиенту неправильную URL-схему - смотрите RFC-3986 : Uniform Resource Identifier (URI): Generic Syntax ([RFC-3986](https://github.com/michaellukashov/Far-NetBox/files/10780316/RFC-3986.chm.zip) en-US, 61 стр.) FileZilla Client 3.63.1 выводит в лог:
```
Статус:	Отключен от сервера
Статус:	Определение IP-адреса для www.cmegroup.com
Статус:	Соединяюсь с 104.66.121.188:21...
Статус:	Не удалось установить соединение с "ETIMEDOUT - Превышено время ожидания соединения".
Ошибка:	Невозможно подключиться к серверу
Статус:	Ожидание повтора...
Статус:	Определение IP-адреса для www.cmegroup.com
Статус:	Соединяюсь с 104.66.121.188:21...
```
т.е. порт 21 (FTP) на сервере закрыт т- видимо он работает только по SSH (порт 22).

**Comment by ujos** [comment]
Я не использовал для подключения HTTP протокол. Видать он там указан ошибочно. Должен быть SSH/SFTP. Если в FileZilla явно указать `sftp://sftpng.cmegroup.com`, то приложение подключается:

```txt
Status:	Connecting to sftpng.cmegroup.com...
Status:	Using username "cmeconfig". 
Status:	Connected to sftpng.cmegroup.akadns.net
Status:	Retrieving directory listing...
Status:	Listing directory /
Status:	Directory listing of "/" successful
```

**Comment by ujos** [comment]
И может еще добавить отображение информации об ошибке? Потому как сейчас окно подключения закрывыется без какой-либо причины.

**Comment by VictorVG** [comment]
Так я же написал выше - видимо разработчик данного сайта думал о чём угодно, но не о правильности смысла того, что пишет. 

Это идёт в первом абзаце [**MDP 3.0 - FTP and SFTP Site Information**](https://www.cmegroup.com/confluence/display/EPICSANDBOX/MDP+3.0+-+FTP+and+SFTP+Site+Information):
> CME provides an FTP (https://www.cmegroup.com/ftp) and SFTP (sftpng.cmegroup.com) site to 
> disseminate MDP 3.0 schemas and market data configuration information. This site contains the > Schema and Configuration files for all events, Security Definition flat files, and Market Schedule 
> files for the New Release and Production environments. Schema and market data configuration
> details for the production environment are only available to customers after the certification 
> process is complete. CME Group recommends clients use SFTP over FTP to access configuration
> files.

и тут я бессилен ибо сию инструкцию как и сайт сегодня в первый раз в глаза увидел.

**Comment by ujos** [comment]
Хм... лог от плагина ведь [приатачил](https://github.com/michaellukashov/Far-NetBox/files/10776954/sftpng.cmegroup.com.log.zip) еще в самом начале. И FileZilla у меня подключилась, писал об этом выше.

**Comment by ujos** [comment]
Для записи, еще два месяца назад плагин работал. Сейчас не работает. Скорее всего поменялся сервер на той стороне

**Comment by ujos** [comment]
> и тут я бессилен ибо сию инструкцию как и сайт сегодня в первый раз в глаза увидел.

То есть проблема не в инструкции. Там все понятно, что нужно стучаться в "sftpng.cmegroup.com" на порт 22 (SSH).

**Comment by VictorVG** [comment]
Могли что-то поменять. По одному моменту времени сказатьо нельзя.

**Comment by ujos** [comment]
Согласно WinScp, версия протокола SFTP-6 
![sftp6](https://user-images.githubusercontent.com/70940/222672383-f35180e4-f262-4a37-b167-6609c32f0779.png)

**Comment by VictorVG** [comment]
Подождём,  плагин в доработке.

**Comment by michaellukashov** [comment]
подключение работает в последней версии плагина 24.1.1.576
можно взять отсюда
https://nightly.link/michaellukashov/Far-NetBox/workflows/release/main?preview
