### ISSUE TITLE
New version crashes on some contitions

### ISSUE THREAD

**Issue by pasha-zzz** [michaellukashov/Far-NetBox#330]
1. On try to connect any session (ENTER in plugin panel).
2. When try to save new session with password or edit session password.
[CrashLogs.zip](https://github.com/michaellukashov/Far-NetBox/files/13609636/CrashLogs.zip)

**Comment by VictorVG** [comment]
При попытке соединится с FTP используя существующую запись сессии сразу падаем:
> Summary
> ======================================================================
> Exception: 0xC0000005 - STATUS_ACCESS_VIOLATION
> Details:   Memory at FFFFFFFFFFFFFFFC could not be read
> errno:     0x00000000 - No error
> LastError: 0x00000000 - Операция успешно завершена.
> NTSTATUS:  0xC000007C - Попытка ссылки на несуществующий токен. Как правило, это происходит при ссылке на токен, связанный с потоком команд, не олицетворяющим клиента.
> Address:   0x00172D5F - NetBox.dll!tinyxml2::XMLPrinter::CompactMode+0x3E43
> Function:  ProcessPanelInputW
> Source:    
> File:      .\Far\plugins\netbox\NetBox.dll
> Plugin:    NetBox 23.12.546.0 (SFTP/FTP(S)/SCP/WebDAV client for FAR 3.0 x86/x64, Mikhail Lukashov)
OpenSSL 3.20 стоит, Xeon E5 2697 v2 / 128 Gb PC3-14900L Quad Cannael (4 x 32 Gb LRDIMM DDR3-1866) / чипсет C602 / GTX 1660 Ti, "разгона" нет, ОС Win 7 SP1 x86-64. 

логи:

[Far_20231209_132030447_4200.zip](https://github.com/michaellukashov/Far-NetBox/files/13624227/Far_20231209_132030447_4200.zip)
[Far_20231209_132112759_6072.zip](https://github.com/michaellukashov/Far-NetBox/files/13624228/Far_20231209_132112759_6072.zip)

**Comment by pasha-zzz** [comment]
Resolved in RC
