### ISSUE TITLE
Множественные ошибки в диалоге изменения атрибутов файла

### ISSUE THREAD

**Issue by ssvine** [michaellukashov/Far-NetBox#335]
Пофиксил разные ошибки в этом диалоге + добавил несколько фичей: [pull request](https://github.com/michaellukashov/Far-NetBox/pull/334)

- нельзя видеть и устанавливать правильные права доступа
- при некоторых условиях не получается изменить владельца и группу
- чекбокс Set attributes recursively не виден, если отображается диалог на ссылке
- включение и выключение доступности кнопки Ok неверное (в фиксах она теперь доступна только когда пользователь сделал хоть какое-то изменение и при этом нет ошибки, типа незаполненного поля owner/group в случаях, когда там должно быть значение)
- то же самое с парой чекбоксов recursive и add X to directories (в фиксах теперь учтены все возможные варианты состояний этих чекбоксов)
- при установке прав на файлах FTP, возникают assert'ы
- список юзеров или групп в соответствующих выпадающих списках для владельца и группы теперь обогащается всеми возможными вариантами имён юзеров или групп (если выделено несколько файлов с разными именами юзеров или групп). Также в список имён юзера добавляется текущий залогиненный юзер. Пофикшена сортировка в этом списке, а также уникальность значений
- невозможно изменить числовые uid/gid, если сервер не поддерживает работу со строковыми именами юзера или группы. Теперь если вызываем диалог изменения атрибутов на подобном сервере, то показываем числовое поле для ввода нового значения uid/gid, а рядом для справки выводим текстовое имя юзера / группы, когда оно есть. Выглядит так:

<img width="448" alt="attrs" src="https://github.com/michaellukashov/Far-NetBox/assets/79405160/f6d9c1cc-1c05-4d23-b761-625dfab25b96">

**Comment by michaellukashov** [comment]
Thanks, added
