### ISSUE TITLE
Множество небольших багов

### ISSUE THREAD

**Issue by ssvine** [michaellukashov/Far-NetBox#339]
В [пулл реквесте](https://github.com/michaellukashov/Far-NetBox/pull/338) пофикшены баги:

- падение при открытии диалога создания ссылки (Alt-F6)
- падение при открытии диалога "Keep remote directory up to date"
- в редакторе сессии на вкладке Tunnel выпадающий список Local tunnel port содержит некорректные значения
- выбранные настройки kex неправильно используются
- избыточная новая строка в редакторе сессии на вкладке Connect перед чекбоксом "Optimize connection buffer size"
- скрытый за списком шифров чекбокс в редакторе сессий на вкладке SSH и вылезающий за габариты список выбора алгоритмов kex
- не работает кнопка Connect из редактора сессии

**Comment by michaellukashov** [comment]
Thanks, added
