### ISSUE TITLE
Фикс интерфейса функции Find

### ISSUE THREAD

**Issue by ssvine** [michaellukashov/Far-NetBox#345]
Недавний коммит привёл к тому, что 2 теста стали фейлиться. Это произошло из-за разных ожиданий от того, что делает функция Find.

В [пулл реквесте](https://github.com/michaellukashov/Far-NetBox/pull/344) сделано исправление этой ситуации. Функция теперь работает так:

1. В функцию Find добавлен параметр `bool leftmost = true`, теперь она может искать и самый левый, и самый правый элемент в **отсортированном** списке (это актуально для dupAccept - когда в списке могут присутствовать несколько одинаковых элементов). Параметр по умолчанию позволяет не делать изменения в старых местах вызова этой функции.
2. В случае когда список неотсортированный, результат поиска отсутствующего элемента приводит к записи значения `nb::NPOS` в аргумент `Index` (как раз один из тестов на это рассчитывает).
3. В случае отсортированного списка, поиск отсутствующего элемента приводит к записи в аргумент `Index` позиции, в которую нужно вставить элемент, чтобы список сохранял свойство отсортированности.

**Comment by michaellukashov** [comment]
Спасибо!
