### ISSUE TITLE
Правка ширины диалогов

### ISSUE THREAD

**Issue by ssvine** [michaellukashov/Far-NetBox#355]
В некоторых диалоговых окнах текст (русский или английский) или контролы налезают на границу окна. В [пулл реквесте](https://github.com/michaellukashov/Far-NetBox/pull/347) сделано исправление размеров окон и поправлено выравнивание некоторых элементов:

* Ширина диалога редактирования сессии, вкладка SFTP, на которой также выравнены элементы
* Ширина диалога "настройки отображения панели"
* Ширина диалога "настройки передачи данных / transfer settings" и разделитель "общие настройки"

**Comment by michaellukashov** [comment]
Спасибо
