### ISSUE TITLE
Копирование информации в диалоге Server and protocol information сломано

### ISSUE THREAD

**Issue by ssvine** [michaellukashov/Far-NetBox#357]
В диалоге "Server and protocol information" при нажатии на кнопку "Copy to clipboard" копируется не пойми что.

Кроме того, в самом диалоге обрезается поле "SSH implementation". Как оказалось, из-за ошибки в функции RightStr.

Пофикшено в этом [пулл реквесте](https://github.com/michaellukashov/Far-NetBox/pull/349).

**Comment by michaellukashov** [comment]
Спасибо
