### ISSUE TITLE
Падение при выполнении команды "Open in PuTTY"

### ISSUE THREAD

**Issue by ssvine** [michaellukashov/Far-NetBox#358]
В [пулл реквесте](https://github.com/michaellukashov/Far-NetBox/pull/350) пофикшено:
    
* Само падение из-за того, что деструктор TStoredSessionList удаляет объекты, которые удаляются базовым классом
* Недоступность ключей PuTTY в реестре, т.к. плагин обращается за ними к корневому разделу реестра HKLM, а не к HCU
* Функция DoExecuteShell, которая вместо исполнения копирует команду в буфер обмена. Этот же фикс позволяет запускать Pageant и PuTTYgen из меню команд

**Comment by michaellukashov** [comment]
Спасибо
