### ISSUE TITLE
В диалоге редактирования сессии наведение мыши на открытый выпадающий список приводит к перерисовке диалога

### ISSUE THREAD

**Issue by ssvine** [michaellukashov/Far-NetBox#360]
Если в диалоге редактирования сессии раскрыть выпадающий список выбора протокола и поводить над разными пунктами мышью или с помощью клавиатуры, то диалог постоянно изменяется под протокол, который подсвечен в выпадающем списке в данный момент. Если приглядется, то через некоторое время можно заметить, что изменения диалога не соответствуют подсвечиваемому пункту.
    
Это наблюдается не только для списка выбора протокола, но также для типа шифрования и прокси.
    
[Пулл реквест](https://github.com/michaellukashov/Far-NetBox/pull/352) запрещает обновляться диалогу пока не произойдёт окончательный выбор пункта.

**Comment by michaellukashov** [comment]
Спасибо
