### ISSUE TITLE
В диалоге редактирования сессии неправильно включаются/отключаются кнопки Up/Down в списках выбора шифров и KEX

### ISSUE THREAD

**Issue by ssvine** [michaellukashov/Far-NetBox#361]
Если походить по элементам в списках выбора шифра или KEX, то можно заметить, что отключение кнопок Up/Down происходит неправильно.
[Пулл реквест](https://github.com/michaellukashov/Far-NetBox/pull/353) исправляет данную ситуацию.

**Comment by michaellukashov** [comment]
Спасибо
