### ISSUE TITLE
Исправления для cmake

### ISSUE THREAD

**Issue by ssvine** [michaellukashov/Far-NetBox#366]
[Пулл-реквест](https://github.com/michaellukashov/Far-NetBox/pull/365) содержит следующие исправления.

1. Для `multi-config` генераторов `CMake`, к которым относится генератор `Visual Studio`, не подходит использование переменной `CMAKE_BUILD_TYPE`, когда на её значении основывается выбор дебажной или релизной библиотеки:

- Сейчас, когда я генерирую файлы проекта, в `Visual Studio` разные конфигурации (`Debug`, `MinSizeRel`, `RelWithDebInfo`, `Release`) все подключают дебажные версии `CRT`: `libcmtd.lib` и `libcpmtd.lib`, поэтому все проекты, кроме `Debug` не могут скомпоноваться.

- То же самое будет, если я присвою переменной `CMAKE_BUILD_TYPE` значение, например, `RelWithDebInfo`. В этом случае во всех конфигурациях будут подключены `libcmt.lib` и `libcpmt.lib`, поэтому, в свою очередь, `Debug` не сможет скомпоноваться.

2. Фактически то же самое происходит в `add_custom_command`, тут приходится использовать `cmake-generator-expressions`, чтобы разные конфигурации получили правильные пути для копирования.

3. В ucm_add_flags в двух случаях используется добавление флага `/DEBUG`, что приводит к установке переменной `EBUG`. Если я правильно понял, тут имелось в виду, что нужно `/DDEBUG` для установки переменной `DEBUG`.

Я проверил эти фиксы для `Visual Studio`, но не проверял для `Ninja`, которое используется в `Actions`. По идее, оно должно и там работать ...

**Comment by ssvine** [comment]
Обнаружил ещё один баг:

В `target_compile_definitions` попадают не только дефайны, но и опции компиляции, которые из-за этого не будут задействованы как опции, что может привести к разным ошибкам (об этом ниже).

Короче говоря, проблема в том, что `target_compile_definitions`  может содержать *только* дефайны, а `target_compile_options` может содержать и опции, и дефайны.

Обновил пулл реквест, где отдельным коммитом раскидал опции и дефайны по разным директивам.

Проблема с опциями привела к тому, что при компиляции конфигурации `Release` в `Visual Studio 2022` для платформы `x64` получался плагин, который падал при попытке коннекта к серверу.

**Comment by ssvine** [comment]
Плюс ещё один фикс: удаляем флаг `/TC`, чтобы компиляция в CI прошла успешно.

**Comment by ssvine** [comment]
Последний штрих: оказалось что `DLL` экспортирует огромное количество (471 шт.) ненужных функций `fmt` и `tinyxml2`. Отключил их экспорт.

**Comment by michaellukashov** [comment]
Спасибо!
