### ISSUE TITLE
Фикс регрессии

### ISSUE THREAD

**Issue by ssvine** [michaellukashov/Far-NetBox#368]
При апдейте исходников [WinSCP](https://github.com/michaellukashov/Far-NetBox/commit/d62135e20226d0de298167f4f393ec38c9f857ee) произошла регрессия одного из исправлений, предложенного в [gh-364](https://github.com/michaellukashov/Far-NetBox/issues/364)

[Пулл реквест](https://github.com/michaellukashov/Far-NetBox/pull/367) исправляет регрессию. Для удобства я пометил строки комментарием, чтобы в дальнейшем было проще ориентироваться при слияниях.

**Comment by michaellukashov** [comment]
Спасибо, применено
