### ISSUE TITLE
Исправления проблем с таймаутами

### ISSUE THREAD

**Issue by ssvine** [michaellukashov/Far-NetBox#370]
В режиме `SCP` при выполнении команд, которые могут долго выполняться, ничего не выводя в консоль, показывается диалог о не отвечающем хосте. В этом диалоге есть проблемы:

1. невозможно указать, что нужно продолжить ожидание, а кнопка в диалоге позволяет только разорвать соединение
2. нельзя изменить фиксированное время ожидания
3. если команда сделала вывод в консоль, то диалог должен тут же закрыться, так как ожидать больше нечего, но диалог не закрывается до исчерпания фиксированного таймаута

В [пулл реквесте](https://github.com/michaellukashov/Far-NetBox/pull/369) данные проблемы исправлены, при этом:

1. добавлена кнопка `Retry`
2. в диалоге глобальной конфигурации `Endurance settings` добавлена возможность изменить время ожидания ответа от хоста

Также в режиме `SCP/SFTP` параметр `Server response timeout` равный нулю означает "без таймаута", но он не работает и попытка подсоединиться к серверу сразу же показывает диалог о не отвечающем хосте. Эта ошибка также исправлена.

**Comment by michaellukashov** [comment]
Спасибо, применено
