### ISSUE TITLE
Apply command (Ctrl-G) применяется дважды

### ISSUE THREAD

**Issue by ssvine** [michaellukashov/Far-NetBox#372]
Если выделить больше одного файла и нажать на `Ctrl-G`, то можно заметить, что команда выполняется дважды для выделенных файлов. Для примера, можно выполнить команду `echo ! >> abc.txt`  и проверить результат. Если команда выполняется через меню команд, то удвоения не происходит.

[Пулл реквест](https://github.com/michaellukashov/Far-NetBox/pull/371) исправляет проблему.

**Comment by michaellukashov** [comment]
Спасибо, применено
