### ISSUE TITLE
Фикс русской трансляции

### ISSUE THREAD

**Issue by ssvine** [michaellukashov/Far-NetBox#374]
Сообщение "Перемещать удаляемые с сервера файлы в корзину (SFTP)" заменено на "Перемещать перезаписываемые файлы в корзину (SFTP)".
Это соответствует английскому тексту, который правильнее описывает ситуацию ("Preserve overwritten remote files to bin (SFTP only)")

[Пулл реквест](https://github.com/michaellukashov/Far-NetBox/pull/373) для исправления.

**Comment by michaellukashov** [comment]
Спасибо, применено
