### ISSUE TITLE
Показывать сообщения об ошибках

### ISSUE THREAD

**Issue by ssvine** [michaellukashov/Far-NetBox#376]
Заметил, что некоторые ошибки никак не показываются. Например, если создать сессию и попытаться сохранить её с именем, которое уже существует, то пользователю не показывается никаких сообщений о том, что что-то не так.

Причина в том, что многие ошибочные ситуации выбрасывают неспецифическое исключение `Exception`, вроде такого: `throw Exception(FORMAT(GetMsg(NB_SESSION_ALREADY_EXISTS_ERROR), Name));`. Если такое исключение в итоге попадает в функцию `TWinSCPPlugin::ShowExtendedException`, то оно отфильтровывается и не показывается.

[Пулл реквест](https://github.com/michaellukashov/Far-NetBox/pull/375) заставляет функцию `TWinSCPPlugin::ShowExtendedException` показывать все сообщения, содержащие текст ошибки.

**Comment by michaellukashov** [comment]
Спасибо, применено
