### ISSUE TITLE
No Such File or Directory

### ISSUE THREAD

**Issue by CrazyMihey** [michaellukashov/Far-NetBox#377]
An annoying Nuisance was discovered after Manually Installing Far-NetBox x64 24.2.1.580 (Main) on Far Manager 3.0.6226.0 x64: When Displaying The Root Directory (Standard Installation) of FreeBSD, PlugIn shows an Error: «No Such File or Directory…» [First Screen-Shot].
![No Such File or Directory](https://github.com/michaellukashov/Far-NetBox/assets/160349844/1c39b8a3-9e2a-4b92-bdc5-d82f9f567c58)
Switching Protocol from «SFTP» to «SCP» Gives a more detailed Error: «Command ls … Failed …» [Second Screen-Shot].
![Command ls Failed](https://github.com/michaellukashov/Far-NetBox/assets/160349844/8ef7b002-fcdd-4e06-845e-bd54950b8594)
As I understand, the Problem is that Root «/» on FreeBSD contains a Symbolic Link «/sys» to the Source Catalog «/usr/src/sys», which is not Created Yet. And maybe newer will Exist in Some Installations.
```
root@Msk.CrazyMihey.Ru:~ # ls -lsAFG "/"
total 32885
…
    0 lrwxr-xr-x   1 root  wheel           11 Apr  9  2021 sys@ -> usr/src/sys
    4 drwxrwxrwt   7 root  wheel          512 Feb 17 04:15 tmp/
    4 drwxr-xr-x  14 root  wheel          512 Apr 27  2021 usr/
…

```
```
root@Msk.CrazyMihey.Ru:~ # ls -lsAFG "/usr/src"
total 0
```
ReMoving «/sys» stops NetBox from Reporting Error Every Time on Root.
So, the Problem is NetBox (with DeFailt Settings) Produces an Error when meets a Link to an UnExisting Object. I Hope It is not too Difficult to Fix?
Old Version of NetBox (Master), Included in Current Distributions of Far Manager, did not have This Error, but is Very-Very Old, does not Understand PPK «PuTTY-User-Key-File-3» and can not Use RSA WithOut MD5-Hash (Deprecated on New Versions of OpenSSH due to Collisions), so Is UnUseAble Now.
Why does Far Manager still include 7-Years Old Version?

**Comment by michaellukashov** [comment]
Please try new version 24.2.1.589
https://nightly.link/michaellukashov/Far-NetBox/workflows/release/main?preview

**Comment by michaellukashov** [comment]
Created PR: https://github.com/FarGroup/Far-NetBox/pull/43
