### ISSUE TITLE
Netbox always crashes while connecting

### ISSUE THREAD

**Issue by skipik** [michaellukashov/Far-NetBox#414]
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 --------------------------------------------------------------------------
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 NetBox Version 24.2.2 beta (Build Build 595) (OS 10.0.22631 – Windows 10 Enterprise)
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Configuration: NetBox 3\
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Log level: Debug 2
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Local account: DESKTOP-U2LVAL6\User
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Working directory: C:\Users\User\Downloads
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Process ID: 3404
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Ancestor processes:
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Command-line:
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Time zone: Current: GMT+3 (RTZ 2 (зима)), No DST
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Login time: 26.02.2024 21:22:00
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 --------------------------------------------------------------------------
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Session name: RARLabs (FTP) (Site)
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Host name: ftp.rarlabs.com (Port: 21)
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 User name: anonymous (Password: No, Key file: No, Passphrase: No)
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Transfer Protocol: FTP
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Ping type: Dummy, Ping interval: 30 sec; Timeout: 90 sec
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Disable Nagle: Yes
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Proxy: None
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Send buffer: 262144
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 UTF: Off
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 FTPS: None [Client certificate: No]
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 FTP: Passive: Yes [Force IP: Auto]; MLSD: Auto [List all: Auto]; HOST: Auto
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Local directory: default, Remote directory: /rar/, Update: No, Cache: No
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Cache directory changes: No, Permanent: No
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Recycle bin: Delete to: No, Overwritten to: No, Bin path:
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 Timezone offset: 0h 0m
> 2024-02-26 21:22:00.881 . 2024-02-26 21:22:00.881 --------------------------------------------------------------------------
> 2024-02-26 21:22:00.908 . 2024-02-26 21:22:00.908 Connecting to ftp.rarlabs.com ...
> 2024-02-26 21:22:00.908 . 2024-02-26 21:22:00.908 Connection pending
> 2024-02-26 21:22:00.955 . 2024-02-26 21:22:00.955 Connected with ftp.rarlabs.com. Waiting for welcome message...
> 2024-02-26 21:22:00.991 . 2024-02-26 21:22:00.991 Read 36 bytes
> 2024-02-26 21:22:01.053 < 2024-02-26 21:22:01.053 220 Welcome to rarlab FTP service.
> 2024-02-26 21:22:01.053 > 2024-02-26 21:22:01.053 USER anonymous
> 2024-02-26 21:22:01.053 . 2024-02-26 21:22:01.053 Read 34 bytes
> 2024-02-26 21:22:01.053 < 2024-02-26 21:22:01.053 331 Please specify the password.

[bug_report.txt](https://github.com/michaellukashov/Far-NetBox/files/14409336/bug_report.txt)

P.S. let me know if you need dump files - I'll send them directly to you.
P.S.S. it started to happen just on recent builds btw, everything was fine ~ 3-5 days ago

**Comment by skipik** [comment]
[far.mdmp.zip](https://github.com/michaellukashov/Far-NetBox/files/14409391/far.mdmp.zip)

1. Far -> Alt+F2 -> Netbox -> RarLabs (FTP) -> Enter - Crash

RarLabs (FTP)

```
<?xml version="1.0" encoding="UTF-8"?>
<NetBox version="2.1">
    <Sessions>
        <Session name="RARLabs%20(FTP)">
            <Version>24.4.85</Version>
            <HostName>ftp.rarlabs.com</HostName>
            <PortNumber>21</PortNumber>
            <PingType>2</PingType>
            <Timeout>90</Timeout>
            <UserName>anonymous</UserName>
            <FSProtocol>FTP</FSProtocol>
            <RemoteDirectory>/rar/</RemoteDirectory>
            <UpdateDirectories>No</UpdateDirectories>
            <TimeDifferenceAuto>No</TimeDifferenceAuto>
            <SFTPMaxVersion>0</SFTPMaxVersion>
            <LoginType>0</LoginType>
        </Session>
    </Sessions>
</NetBox>
```

**Comment by Zeroes1** [comment]
Проблема появилась при переходе с NetBox 24.2.2.591 на NetBox 24.2.2.592

проблема если пытаемся законектится с пустым паролем по FTP . По крайней мере при аккаунте anonymous.

**Comment by michaellukashov** [comment]
NetBox 24.2.3.596.143 should work

**Comment by Zeroes1** [comment]
now - fine!, thanx!

**Comment by skipik** [comment]
Починилось. Спасибо!
