### ISSUE TITLE
Logic of copy operation

### ISSUE THREAD

**Issue by yjh-styx** [michaellukashov/Far-NetBox#417]
Create SSH-connect and initiate copy (F5) directory with files from local to server.
Directory already present on server. -- 
ERROR: 4 (create a directory that already exists)
After answer skip/skipall operation continued normally

**Comment by ssvine** [comment]
You can test the fix #471: get the built [artifact](https://ci.appveyor.com/api/buildjobs/vfsquevdpdhgpndg/artifacts/Far3_x64%2FPlugins%2FNetBox-x64.zip) (x64)
