### ISSUE TITLE
Невозможно использовать прокси для подключений по FTP

### ISSUE THREAD

**Issue by ssvine** [michaellukashov/Far-NetBox#419]
[Пулл реквест](https://github.com/michaellukashov/Far-NetBox/pull/418) фиксит несколько проблем, которые привели к невозможности использовать прокси для `FTP`:

- неправильное определение типа прокси для `FTP`
- повреждение памяти из-за недостаточного размера буфера строки

**Comment by michaellukashov** [comment]
Спасибо!
