### ISSUE TITLE
Ошибка при чтении ссылок (SCP) и неоптимальный порядок чтения

### ISSUE THREAD

**Issue by ssvine** [michaellukashov/Far-NetBox#421]
В режиме `SCP` некоторые последовательности ссылок могут читаться неправильно.

Пример. Листинг текущей директории:
```bash
$ ls -la python*
lrwxrwxrwx 1 root root  7 мая 19  2020 python -> python3
lrwxrwxrwx 1 root root 16 мая 19  2020 python3 -> /usr/bin/python3
```

Листинг директории `/usr/bin`:
```bash
$ ls -la /usr/bin/python*
lrwxrwxrwx 1 root root       9 окт 25  2018 /usr/bin/python3 -> python3.6
-r-xr-xr-x 2 root root 4526456 мар 10  2023 /usr/bin/python3.6
```

После чтения ссылки `python3` плагин увидит, что она указывает на `/usr/bin/python3`, которая тоже ссылка. Она, в свою очередь, указывает на файл `python3.6`, расположеный в директории `/usr/bin`, но плагин не учитывает относительность ссылки и начнёт читать её в текущей директории.

[Пулл реквест](https://github.com/michaellukashov/Far-NetBox/pull/420) исправляет ошибку с чтением ссылок.

Когда разбирался с этой ошибкой, обнаружил, что ссылки читаются неоптимально - дважды. Первый раз при чтении директории, второй раз при вызове функции `GetFindDataW`.

Ссылки читаются с одной целью - узнать, директория это или нет. В пулл реквесте схема чтения ссылок переделана так, чтобы тип устанавливался сразу при чтении директории и не возникала необходимость перечитывать их повторно. Для некоторых серверов со слабым каналом и большим количеством ссылок можно получить увеличение скорости чтения директории почти в 2 раза. Для примера можно привести директорию `ftp@cygwin.mirror.rafal.ca:/Debian/debian/dists`, которая на моих тестах читалась за 26 секунд, а стала за 14.

Помимо этого внесены следующие изменения:

- Сделано логирование команд `SCP` (оказалось, что команды вообще никак не логировались, что не удобно)
- `Amazon S3` не поддерживает резолвинг ссылок, но в диалоге редактирования сессии чекбокс `Resolve symbolic links` был доступен для изменения

**Comment by michaellukashov** [comment]
Спасибо, добавлено в v24.3.0.597
