### ISSUE TITLE
SFTP Transfer speed

### ISSUE THREAD

**Issue by relictMarauder** [michaellukashov/Far-NetBox#464]
Hi,

i was stick with old version 2.4.5 build 545. At this version speed by SFTP connection is about 40-50 Megabytes/sec
after switch to recent one(NetBox 24.4.1.601) the transfer speed is droped to 3-4 Megabytes/sec (same behavior for all versions 24.x which i tested since v24.1.1.570))

**Comment by Px-x64** [comment]
What about [NetBox 23.12.0.546 07.12.2023](https://github.com/michaellukashov/Far-NetBox/releases/tag/v23.12.0.546), does it also have the same speed problem? Also iirc there were intermediate builds published in [this forum topic](https://forum.farmanager.com/viewtopic.php?p=176940#p176940), try to test them too to find out when the speed issue first appeared

**Comment by relictMarauder** [comment]
The Problem was enabled debug-info :) After disabling logging the speed was restored.
