### ISSUE TITLE
Uploading folder to already existing one fails

### ISSUE THREAD

**Issue by bol-van** [michaellukashov/Far-NetBox#470]
Connect to ssh

on local system create an empty folder
upload to ssh
upload to ssh again. get error

had to revert to ~DEC 2023 version which works

**Comment by ssvine** [comment]
You can test the fix #471: get the built [artifact](https://ci.appveyor.com/api/buildjobs/vfsquevdpdhgpndg/artifacts/Far3_x64%2FPlugins%2FNetBox-x64.zip) (x64)

**Comment by bol-van** [comment]
Error is gone. Thanx
